export const playerDatabase = {
  europe: {
    '1940-1950': [
      { name: 'Stanley Matthews', country: 'England', position: 'Forward', clubs: ['Stoke City', 'Blackpool'], birthYear: 1915, worldCup: false, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 174, hair: 'light', beard: false },
      { name: 'Ferenc Puskás', country: 'Hungary', position: 'Forward', clubs: ['Real Madrid', 'Budapest Honvéd', 'Kispest'], birthYear: 1927, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Alfredo Di Stéfano', country: 'Argentina', position: 'Forward', clubs: ['Real Madrid', 'River Plate', 'Millonarios'], birthYear: 1926, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 176, hair: 'light', beard: false },
      { name: 'Gunnar Nordahl', country: 'Sweden', position: 'Forward', clubs: ['AC Milan'], birthYear: 1921, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 180, hair: 'blonde', beard: false },
      { name: 'Josef Masopust', country: 'Czechia', position: 'Midfielder', clubs: ['Dukla Prague'], birthYear: 1931, worldCup: false, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false }
    ],
    '1950-1960': [
      { name: 'Johan Cruyff', country: 'Netherlands', position: 'Forward', clubs: ['Ajax', 'Barcelona', 'Feyenoord'], birthYear: 1947, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'George Best', country: 'Northern Ireland', position: 'Forward', clubs: ['Manchester United'], birthYear: 1946, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Franz Beckenbauer', country: 'Germany', position: 'Defender', clubs: ['Bayern Munich'], birthYear: 1945, worldCup: true, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 181, hair: 'light', beard: false },
      { name: 'Gerd Müller', country: 'Germany', position: 'Forward', clubs: ['Bayern Munich'], birthYear: 1945, worldCup: true, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 176, hair: 'dark', beard: false },
      { name: 'Bobby Charlton', country: 'England', position: 'Midfielder', clubs: ['Manchester United'], birthYear: 1937, worldCup: true, euro: false, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'light', beard: false },
      { name: 'Dino Zoff', country: 'Italy', position: 'Goalkeeper', clubs: ['Juventus'], birthYear: 1942, worldCup: true, euro: true, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 182, hair: 'dark', beard: false },
      { name: 'Eusébio', country: 'Portugal', position: 'Forward', clubs: ['Benfica'], birthYear: 1942, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Lev Yashin', country: 'Russia', position: 'Goalkeeper', clubs: ['Dynamo Moscow'], birthYear: 1929, worldCup: false, euro: true, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 189, hair: 'dark', beard: false },
      { name: 'Gianni Rivera', country: 'Italy', position: 'Midfielder', clubs: ['AC Milan'], birthYear: 1943, worldCup: false, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Denis Law', country: 'Scotland', position: 'Forward', clubs: ['Manchester United'], birthYear: 1940, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false }
    ],
    '1960-1970': [
      { name: 'Michel Platini', country: 'France', position: 'Midfielder', clubs: ['Juventus', 'AS Nancy', 'Saint-Étienne'], birthYear: 1955, worldCup: false, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: true, height: 178, hair: 'dark', beard: false },
      { name: 'Karl-Heinz Rummenigge', country: 'Germany', position: 'Forward', clubs: ['Bayern Munich'], birthYear: 1955, worldCup: true, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: true, ligue1: false, height: 182, hair: 'dark', beard: false },
      { name: 'Paolo Rossi', country: 'Italy', position: 'Forward', clubs: ['Juventus'], birthYear: 1956, worldCup: true, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Zbigniew Boniek', country: 'Poland', position: 'Midfielder', clubs: ['Juventus', 'Roma'], birthYear: 1956, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Jean Tigana', country: 'France', position: 'Midfielder', clubs: ['Bordeaux'], birthYear: 1955, worldCup: false, euro: true, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 174, hair: 'dark', beard: false },
      { name: 'Kenny Dalglish', country: 'Scotland', position: 'Forward', clubs: ['Liverpool', 'Celtic'], birthYear: 1951, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Kevin Keegan', country: 'England', position: 'Forward', clubs: ['Liverpool', 'Hamburg'], birthYear: 1951, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Bryan Robson', country: 'England', position: 'Midfielder', clubs: ['Manchester United', 'West Bromwich'], birthYear: 1957, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Preben Elkjær', country: 'Denmark', position: 'Forward', clubs: ['Verona'], birthYear: 1957, worldCup: false, euro: true, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Igor Belanov', country: 'Ukraine', position: 'Forward', clubs: ['Dynamo Kyiv'], birthYear: 1960, worldCup: false, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 179, hair: 'dark', beard: false },
      { name: 'Ruud Gullit', country: 'Netherlands', position: 'Midfielder', clubs: ['AC Milan', 'Chelsea', 'PSV Eindhoven', 'Sampdoria', 'Feyenoord'], birthYear: 1962, worldCup: false, euro: true, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 191, hair: 'dark', beard: false },
      { name: 'Marco van Basten', country: 'Netherlands', position: 'Forward', clubs: ['AC Milan', Ajax'], birthYear: 1964, worldCup: false, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 188, hair: 'blonde', beard: false },
      { name: 'Frank Rijkaard', country: 'Netherlands', position: 'Midfielder', clubs: ['AC Milan', 'Ajax'], birthYear: 1962, worldCup: false, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 190, hair: 'dark', beard: false },
      { name: 'Roberto Baggio', country: 'Italy', position: 'Forward', clubs: ['Juventus', 'AC Milan', 'Inter Milan', 'Brescia'], birthYear: 1967, worldCup: false, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Lothar Matthäus', country: 'Germany', position: 'Midfielder', clubs: ['Bayern Munich', 'Inter Milan'], birthYear: 1961, worldCup: true, euro: true, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: true, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Gary Lineker', country: 'England', position: 'Forward', clubs: ['Barcelona', 'Tottenham'], birthYear: 1960, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Jean-Pierre Papin', country: 'France', position: 'Forward', clubs: ['Marseille', 'AC Milan'], birthYear: 1963, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 173, hair: 'dark', beard: false },
      { name: 'Matthias Sammer', country: 'Germany', position: 'Defender', clubs: ['Borussia Dortmund'], birthYear: 1967, worldCup: false, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 182, hair: 'blonde', beard: false },
      { name: 'Hristo Stoichkov', country: 'Bulgaria', position: 'Forward', clubs: ['Barcelona'], birthYear: 1966, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Paul Gascoigne', country: 'England', position: 'Midfielder', clubs: ['Tottenham', 'Lazio', 'Newcastle'], birthYear: 1967, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Alan Shearer', country: 'England', position: 'Forward', clubs: ['Blackburn Rovers', 'Newcastle'], birthYear: 1970, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false }
    ],
    '1970-1980': [
      { name: 'Edwin van der Sar', country: 'Netherlands', position: 'Goalkeeper', clubs: ['Ajax', 'Juventus', 'Fulham', 'Manchester United'], birthYear: 1970, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 198, hair: 'light', beard: false },
      { name: 'Zinedine Zidane', country: 'France', position: 'Midfielder', clubs: ['Juventus', 'Real Madrid'], birthYear: 1972, worldCup: true, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 185, hair: 'bald', beard: false },
      { name: 'Thierry Henry', country: 'France', position: 'Forward', clubs: ['Arsenal', 'Barcelona'], birthYear: 1977, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 188, hair: 'dark', beard: false },
      { name: 'Pavel Nedvěd', country: 'Czech Republic', position: 'Midfielder', clubs: ['Juventus', 'Lazio'], birthYear: 1972, worldCup: false, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 177, hair: 'blonde', beard: false },
      { name: 'Raúl', country: 'Spain', position: 'Forward', clubs: ['Real Madrid', 'Schalke 04'], birthYear: 1977, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Andriy Shevchenko', country: 'Ukraine', position: 'Forward', clubs: ['AC Milan', 'Chelsea', 'Dynamo Kyiv'], birthYear: 1976, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Michael Owen', country: 'England', position: 'Forward', clubs: ['Liverpool', 'Real Madrid', 'Manchester United', 'Newcastle'], birthYear: 1979, worldCup: false, euro: false, championsLeague: false, ballonDor: true, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Francesco Totti', country: 'Italy', position: 'Forward', clubs: ['Roma'], birthYear: 1976, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Andrea Pirlo', country: 'Italy', position: 'Midfielder', clubs: ['AC Milan', 'Juventus'], birthYear: 1979, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 177, hair: 'dark', beard: true },
      { name: 'Frank Lampard', country: 'England', position: 'Midfielder', clubs: ['Chelsea', 'West Ham United', 'Manchester City'], birthYear: 1978, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 184, hair: 'dark', beard: false },
      { name: 'Steven Gerrard', country: 'England', position: 'Midfielder', clubs: ['Liverpool'], birthYear: 1980, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Xavi', country: 'Spain', position: 'Midfielder', clubs: ['Barcelona'], birthYear: 1980, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 170, hair: 'dark', beard: false },
      { name: 'Kaká', country: 'Brazil', position: 'Midfielder', clubs: ['AC Milan', 'Real Madrid'], birthYear: 1982, worldCup: true, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 186, hair: 'dark', beard: false },
      { name: 'Ronaldo Nazário', country: 'Brazil', position: 'Forward', clubs: ['Barcelona', 'Inter Milan', 'Real Madrid', 'AC Milan', 'PSV Eindhoven'], birthYear: 1976, worldCup: true, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 183, hair: 'bald', beard: false },
      { name: 'Ronaldinho', country: 'Brazil', position: 'Midfielder', clubs: ['Barcelona', 'AC Milan', 'PSG'], birthYear: 1980, worldCup: true, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 181, hair: 'dark', beard: true },
      { name: 'Gabriel Batistuta', country: 'Argentina', position: 'Forward', clubs: ['Fiorentina', 'Roma'], birthYear: 1969, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 185, hair: 'light', beard: false }
    ],
    '1980-1990': [
      { name: 'Cristiano Ronaldo', country: 'Portugal', position: 'Forward', clubs: ['Sporting CP', 'Manchester United', 'Real Madrid', 'Juventus', 'Al-Nassr'], birthYear: 1985, worldCup: false, euro: true, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 187, hair: 'dark', beard: false },
      { name: 'Luka Modrić', country: 'Croatia', position: 'Midfielder', clubs: ['Tottenham', 'Real Madrid'], birthYear: 1985, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 172, hair: 'light', beard: false },
      { name: 'Andrés Iniesta', country: 'Spain', position: 'Midfielder', clubs: ['Barcelona', 'Vissel Kobe'], birthYear: 1984, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 171, hair: 'dark', beard: false },
      { name: 'Sergio Ramos', country: 'Spain', position: 'Defender', clubs: ['Real Madrid', 'PSG', 'Sevilla'], birthYear: 1986, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 184, hair: 'dark', beard: true },
      { name: 'Manuel Neuer', country: 'Germany', position: 'Goalkeeper', clubs: ['Bayern Munich'], birthYear: 1986, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 193, hair: 'blonde', beard: false },
      { name: 'Wayne Rooney', country: 'England', position: 'Forward', clubs: ['Manchester United', 'Everton', 'DC United'], birthYear: 1985, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 176, hair: 'dark', beard: false },
      { name: 'Mesut Özil', country: 'Germany', position: 'Midfielder', clubs: ['Real Madrid', 'Arsenal'], birthYear: 1988, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Zlatan Ibrahimović', country: 'Sweden', position: 'Forward', clubs: ['Ajax', 'Juventus', 'Inter Milan', 'Barcelona', 'AC Milan', 'PSG', 'Manchester United', 'LA Galaxy'], birthYear: 1981, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: true, bundesliga: false, ligue1: true, height: 195, hair: 'dark', beard: false },
      { name: 'Robert Lewandowski', country: 'Poland', position: 'Forward', clubs: ['Borussia Dortmund', 'Bayern Munich', 'Barcelona'], birthYear: 1988, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: true, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Thomas Müller', country: 'Germany', position: 'Forward', clubs: ['Bayern Munich'], birthYear: 1989, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 186, hair: 'dark', beard: false },
      { name: 'Toni Kroos', country: 'Germany', position: 'Midfielder', clubs: ['Bayern Munich', 'Real Madrid'], birthYear: 1990, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: true, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Cesc Fàbregas', country: 'Spain', position: 'Midfielder', clubs: ['Arsenal', 'Barcelona', 'Chelsea'], birthYear: 1987, worldCup: true, euro: true, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: true },
      { name: 'Gerard Piqué', country: 'Spain', position: 'Defender', clubs: ['Barcelona', 'Manchester United'], birthYear: 1987, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 194, hair: 'dark', beard: false },
      { name: 'David Silva', country: 'Spain', position: 'Midfielder', clubs: ['Manchester City', 'Valencia', 'Real Sociedad'], birthYear: 1986, worldCup: true, euro: true, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 170, hair: 'dark', beard: true },
      { name: 'Arjen Robben', country: 'Netherlands', position: 'Forward', clubs: ['Chelsea', 'Real Madrid', 'Bayern Munich', 'PSV'], birthYear: 1984, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: true, ligue1: false, height: 180, hair: 'bald', beard: false },
      { name: 'Wesley Sneijder', country: 'Netherlands', position: 'Midfielder', clubs: ['Real Madrid', 'Inter Milan', 'Ajax'], birthYear: 1984, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 170, hair: 'dark', beard: false }
    ],
    '1990-2000': [
      { name: 'Kevin De Bruyne', country: 'Belgium', position: 'Midfielder', clubs: ['Manchester City', 'Chelsea', 'Wolfsburg', 'Napoli'], birthYear: 1991, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 181, hair: 'ginger', beard: false },
      { name: 'Harry Kane', country: 'England', position: 'Forward', clubs: ['Tottenham', 'Bayern Munich'], birthYear: 1993, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 188, hair: 'dark', beard: false },
      { name: 'Kylian Mbappé', country: 'France', position: 'Forward', clubs: ['Monaco', 'PSG', 'Real Madrid'], birthYear: 1998, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 178, hair: 'dark', beard: false },
      { name: 'Martin Ødegaard', country: 'Norway', position: 'Midfielder', clubs: ['Real Madrid', 'Arsenal'], birthYear: 1998, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'blonde', beard: true },
      { name: 'Thibaut Courtois', country: 'Belgium', position: 'Goalkeeper', clubs: ['Genk', 'Atlético Madrid', 'Chelsea', 'Real Madrid'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 199, hair: 'dark', beard: false },
      { name: "N'Golo Kanté", country: 'France', position: 'Midfielder', clubs: ['Leicester City', 'Chelsea'], birthYear: 1991, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 168, hair: 'dark', beard: false },
      { name: 'Antoine Griezmann', country: 'France', position: 'Forward', clubs: ['Atletico Madrid', 'Barcelona', 'Real Sociedad'], birthYear: 1991, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 176, hair: 'blonde', beard: false },
      { name: 'Florian Wirtz', country: 'Germany', position: 'Midfielder', clubs: ['Bayer Leverkusen', 'Liverpool'], birthYear: 2003, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Jude Bellingham', country: 'England', position: 'Midfielder', clubs: ['Borussia Dortmund', 'Real Madrid'], birthYear: 2003, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: true, ligue1: false, height: 186, hair: 'dark', beard: false },
      { name: 'Erling Haaland', country: 'Norway', position: 'Forward', clubs: ['Borussia Dortmund', 'Manchester City', 'RB Salzburg', 'Molde', 'Bryne'], birthYear: 2000, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 194, hair: 'blonde', beard: false },
      { name: 'Jamal Musiala', country: 'Germany', position: 'Midfielder', clubs: ['Bayern Munich'], birthYear: 2003, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 184, hair: 'dark', beard: false },
      { name: 'Pedri', country: 'Spain', position: 'Midfielder', clubs: ['Barcelona'], birthYear: 2002, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Gavi', country: 'Spain', position: 'Midfielder', clubs: ['Barcelona'], birthYear: 2004, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false }
    ]
  },
  americas: {
    '1940-1950': [
      { name: 'Pelé', country: 'Brazil', position: 'Forward', clubs: ['Santos'], birthYear: 1940, worldCup: true, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Garrincha', country: 'Brazil', position: 'Forward', clubs: ['Botafogo'], birthYear: 1933, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 169, hair: 'dark', beard: false },
      { name: 'Didí', country: 'Brazil', position: 'Midfielder', clubs: ['Real Madrid', 'Botafogo'], birthYear: 1928, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false }
    ],
    '1950-1960': [
      { name: 'Teófilo Cubillas', country: 'Peru', position: 'Midfielder', clubs: ['Alianza Lima'], birthYear: 1949, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Elías Figueroa', country: 'Chile', position: 'Defender', clubs: ['Internacional'], birthYear: 1946, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Rivelino', country: 'Brazil', position: 'Midfielder', clubs: ['Fluminense'], birthYear: 1946, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 171, hair: 'dark', beard: false }
    ],
    '1960-1970': [
      { name: 'Diego Maradona', country: 'Argentina', position: 'Forward', clubs: ['Napoli', 'Barcelona'], birthYear: 1960, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 165, hair: 'dark', beard: false },
      { name: 'Socrates', country: 'Brazil', position: 'Midfielder', clubs: ['Corinthians'], birthYear: 1954, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 192, hair: 'dark', beard: true },
      { name: 'Romário', country: 'Brazil', position: 'Forward', clubs: ['Barcelona', 'PSV'], birthYear: 1966, worldCup: true, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 169, hair: 'dark', beard: false },
      { name: 'Claudio Caniggia', country: 'Argentina', position: 'Forward', clubs: ['River Plate', 'Boca Juniors'], birthYear: 1967, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 174, hair: 'blonde', beard: false },
      { name: 'Carlos Valderrama', country: 'Colombia', position: 'Midfielder', clubs: ['Montpellier'], birthYear: 1961, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 175, hair: 'blonde', beard: true }
    ],
    '1970-1980': [
      { name: 'Rivaldo', country: 'Brazil', position: 'Midfielder', clubs: ['Barcelona', 'AC Milan'], birthYear: 1972, worldCup: true, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 186, hair: 'dark', beard: false },
      { name: 'Juan Román Riquelme', country: 'Argentina', position: 'Midfielder', clubs: ['Boca Juniors', 'Barcelona', 'Villarreal'], birthYear: 1978, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 182, hair: 'dark', beard: false },
      { name: 'Roberto Carlos', country: 'Brazil', position: 'Defender', clubs: ['Real Madrid'], birthYear: 1973, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 168, hair: 'dark', beard: false },
      { name: 'Claudio López', country: 'Argentina', position: 'Forward', clubs: ['Valencia'], birthYear: 1974, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Alex Aguinaga', country: 'Ecuador', position: 'Midfielder', clubs: ['Necaxa'], birthYear: 1968, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false }
    ],
    '1980-1990': [
      { name: 'Lionel Messi', country: 'Argentina', position: 'Forward', clubs: ['Barcelona', 'PSG', 'Inter Miami'], birthYear: 1987, worldCup: true, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 170, hair: 'dark', beard: true },
      { name: 'Javier Mascherano', country: 'Argentina', position: 'Midfielder', clubs: ['Barcelona', 'Liverpool'], birthYear: 1984, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Dani Alves', country: 'Brazil', position: 'Defender', clubs: ['Barcelona', 'Sevilla', 'PSG', 'Juventus'], birthYear: 1983, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 172, hair: 'dark', beard: false },
      { name: 'Alexis Sánchez', country: 'Chile', position: 'Forward', clubs: ['Barcelona', 'Arsenal', 'Manchester United', 'Udinese', 'Inter Milan'], birthYear: 1988, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 169, hair: 'dark', beard: false },
      { name: 'Andrés Guardado', country: 'Mexico', position: 'Midfielder', clubs: ['Valencia', 'PSV', 'Real Betis'], birthYear: 1986, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 169, hair: 'dark', beard: false },
      { name: 'Tim Howard', country: 'USA', position: 'Goalkeeper', clubs: ['Manchester United', 'Everton'], birthYear: 1979, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 191, hair: 'dark', beard: false }
    ],
    '1990-2000': [
      { name: 'Alphonso Davies', country: 'Canada', position: 'Defender', clubs: ['Bayern Munich'], birthYear: 2000, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Hirving Lozano', country: 'Mexico', position: 'Forward', clubs: ['PSV', 'Napoli'], birthYear: 1995, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Neymar Jr', country: 'Brazil', position: 'Forward', clubs: ['Santos', 'Barcelona', 'PSG', 'Al-Hilal'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 175, hair: 'dark', beard: false },
      { name: 'Federico Valverde', country: 'Uruguay', position: 'Midfielder', clubs: ['Real Madrid'], birthYear: 1998, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 182, hair: 'dark', beard: false },
      { name: 'Christian Pulisic', country: 'USA', position: 'Forward', clubs: ['Borussia Dortmund', 'Chelsea', 'AC Milan'], birthYear: 1998, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: true, ligue1: false, height: 178, hair: 'dark', beard: false }
    ]
  },
  africa: {
    '1950-1960': [
      { name: 'Roger Milla', country: 'Cameroon', position: 'Forward', clubs: ['Saint-Étienne', 'Montpellier'], birthYear: 1952, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 175, hair: 'dark', beard: false },
      { name: 'Rabah Madjer', country: 'Algeria', position: 'Forward', clubs: ['Porto'], birthYear: 1958, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false }
    ],
    '1960-1970': [
      { name: 'Abedi Pele', country: 'Ghana', position: 'Midfielder', clubs: ['Marseille'], birthYear: 1964, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 173, hair: 'dark', beard: false },
      { name: 'George Weah', country: 'Liberia', position: 'Forward', clubs: ['AC Milan', 'PSG', 'Chelsea', 'Manchester City'], birthYear: 1966, worldCup: false, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: true, height: 185, hair: 'dark', beard: false },
      { name: 'Finidi George', country: 'Nigeria', position: 'Forward', clubs: ['Ajax', 'Real Betis'], birthYear: 1971, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false }
    ],
    '1970-1980': [
      { name: 'Samuel Eto\'o', country: 'Cameroon', position: 'Forward', clubs: ['Barcelona', 'Inter Milan', 'Chelsea'], birthYear: 1979, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Didier Drogba', country: 'Ivory Coast', position: 'Forward', clubs: ['Chelsea', 'Marseille', 'Galatasaray'], birthYear: 1978, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 189, hair: 'dark', beard: false },
      { name: 'Jay-Jay Okocha', country: 'Nigeria', position: 'Midfielder', clubs: ['PSG', 'Bolton'], birthYear: 1973, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 173, hair: 'dark', beard: false },
      { name: 'Nwankwo Kanu', country: 'Nigeria', position: 'Forward', clubs: ['Ajax', 'Arsenal'], birthYear: 1976, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 197, hair: 'dark', beard: false },
      { name: 'El Hadji Diouf', country: 'Senegal', position: 'Forward', clubs: ['Liverpool', 'Lens', 'Blackburn'], birthYear: 1981, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 181, hair: 'bald', beard: true }
    ],
    '1980-1990': [
      { name: 'Michael Essien', country: 'Ghana', position: 'Midfielder', clubs: ['Chelsea', 'Lyon', 'Real Madrid', 'AC Milan'], birthYear: 1982, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 177, hair: 'dark', beard: false },
      { name: 'Yaya Touré', country: 'Ivory Coast', position: 'Midfielder', clubs: ['Barcelona', 'Manchester City'], birthYear: 1983, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 188, hair: 'dark', beard: false },
      { name: 'Frédéric Kanouté', country: 'Mali', position: 'Forward', clubs: ['Sevilla', 'West Ham'], birthYear: 1977, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 192, hair: 'dark', beard: false }
    ],
    '1990-2000': [
      { name: 'Mohamed Salah', country: 'Egypt', position: 'Forward', clubs: ['Chelsea', 'Roma', 'Liverpool','Basel'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: true },
      { name: 'Riyad Mahrez', country: 'Algeria', position: 'Forward', clubs: ['Leicester City', 'Manchester City'], birthYear: 1991, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 179, hair: 'dark', beard: true },
      { name: 'Sadio Mané', country: 'Senegal', position: 'Forward', clubs: ['Liverpool', 'Bayern Munich'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 175, hair: 'dark', beard: false }
    ]
  },
  asia: {
    '1950-1960': [
      { name: 'Chung Hae-won', country: 'South Korea', position: 'Forward', clubs: ['Busan IPark'], birthYear: 1959, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false }
    ],
    '1960-1970': [
      { name: 'Hong Myung-bo', country: 'South Korea', position: 'Defender', clubs: ['Bellmare Hiratsuka'], birthYear: 1969, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 182, hair: 'dark', beard: false }
    ],
    '1970-1980': [
      { name: 'Hidetoshi Nakata', country: 'Japan', position: 'Midfielder', clubs: ['Roma', 'Parma'], birthYear: 1977, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Ali Daei', country: 'Iran', position: 'Forward', clubs: ['Bayern Munich', 'Hertha Berlin'], birthYear: 1969, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 192, hair: 'dark', beard: false },
      { name: 'Sami Al-Jaber', country: 'Saudi Arabia', position: 'Forward', clubs: ['Al-Hilal'], birthYear: 1972, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false }
    ],
    '1980-1990': [
      { name: 'Park Ji-Sung', country: 'South Korea', position: 'Midfielder', clubs: ['Manchester United', 'PSV'], birthYear: 1981, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Keisuke Honda', country: 'Japan', position: 'Midfielder', clubs: ['AC Milan', 'CSKA Moscow'], birthYear: 1986, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 182, hair: 'light', beard: false },
      { name: 'Tim Cahill', country: 'Australia', position: 'Midfielder', clubs: ['Everton'], birthYear: 1979, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false }
    ],
    '1990-2000': [
      { name: 'Son Heung-min', country: 'South Korea', position: 'Forward', clubs: ['Tottenham', 'Bayer Leverkusen'], birthYear: 1992, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Takefusa Kubo', country: 'Japan', position: 'Forward', clubs: ['Real Sociedad', 'Real Madrid'], birthYear: 2001, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false }
    ]
  },
  oceania: {
    '1970-1980': [
      { name: 'Ryan Nelsen', country: 'New Zealand', position: 'Defender', clubs: ['Blackburn Rovers', 'Tottenham'], birthYear: 1977, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Mark Viduka', country: 'Australia', position: 'Forward', clubs: ['Leeds United', 'Middlesbrough'], birthYear: 1975, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 188, hair: 'dark', beard: false }
    ],
    '1980-1990': [
      { name: 'Brett Emerton', country: 'Australia', position: 'Midfielder', clubs: ['Blackburn Rovers', 'Feyenoord'], birthYear: 1979, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 179, hair: 'dark', beard: false }
    ]
  }
};
