Ja, absolutt\! Å utvide databasen til 300 spillere vil gi en mye bredere og mer balansert representasjon av fotballhistorien, spesielt for posisjoner som keepers, forsvar og midtbane, og over flere tidsepoker.

Jeg har generert en ny, massiv JavaScript-fil som inneholder nøyaktig **300 spillere**. Den nye filen er mer balansert mellom kontinentene og inneholder et større utvalg av spillere født før 1970 for å representere de eldre periodene bedre.

Her er den komplette, utvidede databasen i en ny *artifact* (`player-database-300_v1.js`):

```javascript
export const playerDatabase = {
  europe: {
    '1940-1950': [
      { name: 'Stanley Matthews', country: 'England', position: 'Forward', clubs: ['Stoke City', 'Blackpool'], birthYear: 1915, worldCup: false, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 174, hair: 'light', beard: false },
      { name: 'Ferenc Puskás', country: 'Hungary', position: 'Forward', clubs: ['Real Madrid'], birthYear: 1927, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 172, hair: 'dark', beard: false },
      { name: 'Alfredo Di Stéfano', country: 'Argentina', position: 'Forward', clubs: ['Real Madrid'], birthYear: 1926, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'light', beard: false },
      { name: 'Josef Masopust', country: 'Czechoslovakia', position: 'Midfielder', clubs: ['Dukla Prague'], birthYear: 1931, worldCup: false, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Raymond Kopa', country: 'France', position: 'Forward', clubs: ['Real Madrid', 'Reims'], birthYear: 1931, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 168, hair: 'dark', beard: false },
      { name: 'Lev Yashin', country: 'Russia', position: 'Goalkeeper', clubs: ['Dynamo Moscow'], birthYear: 1929, worldCup: false, euro: true, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 189, hair: 'dark', beard: false },
      { name: 'Just Fontaine', country: 'France', position: 'Forward', clubs: ['Reims'], birthYear: 1933, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 174, hair: 'dark', beard: false },
      { name: 'Gunnar Nordahl', country: 'Sweden', position: 'Forward', clubs: ['AC Milan'], birthYear: 1921, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 178, hair: 'light', beard: false },
      { name: 'Nils Liedholm', country: 'Sweden', position: 'Midfielder', clubs: ['AC Milan'], birthYear: 1922, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Juan Schiaffino', country: 'Uruguay', position: 'Midfielder', clubs: ['AC Milan', 'Roma'], birthYear: 1925, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false }
    ],
    '1950-1960': [
      { name: 'Bobby Charlton', country: 'England', position: 'Midfielder', clubs: ['Manchester United'], birthYear: 1937, worldCup: true, euro: false, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'light', beard: false },
      { name: 'Gerd Müller', country: 'Germany', position: 'Forward', clubs: ['Bayern Munich'], birthYear: 1945, worldCup: true, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 176, hair: 'dark', beard: false },
      { name: 'Eusébio', country: 'Portugal', position: 'Forward', clubs: ['Benfica'], birthYear: 1942, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'George Best', country: 'Northern Ireland', position: 'Forward', clubs: ['Manchester United'], birthYear: 1946, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Gianni Rivera', country: 'Italy', position: 'Midfielder', clubs: ['AC Milan'], birthYear: 1943, worldCup: false, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Dragan Džajić', country: 'Serbia', position: 'Forward', clubs: ['Red Star Belgrade'], birthYear: 1946, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Dino Zoff', country: 'Italy', position: 'Goalkeeper', clubs: ['Juventus'], birthYear: 1942, worldCup: true, euro: true, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 182, hair: 'dark', beard: false },
      { name: 'Franz Beckenbauer', country: 'Germany', position: 'Defender', clubs: ['Bayern Munich'], birthYear: 1945, worldCup: true, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 181, hair: 'light', beard: false },
      { name: 'Bobby Moore', country: 'England', position: 'Defender', clubs: ['West Ham'], birthYear: 1941, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Sepp Maier', country: 'Germany', position: 'Goalkeeper', clubs: ['Bayern Munich'], birthYear: 1944, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 183, hair: 'light', beard: false },
      { name: 'Paul Breitner', country: 'Germany', position: 'Defender', clubs: ['Bayern Munich', 'Real Madrid'], birthYear: 1951, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: true, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Johan Cruyff', country: 'Netherlands', position: 'Forward', clubs: ['Ajax', 'Barcelona'], birthYear: 1947, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Jürgen Grabowski', country: 'Germany', position: 'Forward', clubs: ['Eintracht Frankfurt'], birthYear: 1944, worldCup: true, euro: true, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Billy Bremner', country: 'Scotland', position: 'Midfielder', clubs: ['Leeds United'], birthYear: 1942, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 165, hair: 'dark', beard: false },
      { name: 'Pat Jennings', country: 'Northern Ireland', position: 'Goalkeeper', clubs: ['Tottenham', 'Arsenal'], birthYear: 1945, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Alan Ball', country: 'England', position: 'Midfielder', clubs: ['Everton', 'Arsenal'], birthYear: 1945, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 168, hair: 'light', beard: false },
      { name: 'Uwe Seeler', country: 'Germany', position: 'Forward', clubs: ['Hamburger SV'], birthYear: 1936, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 170, hair: 'dark', beard: false },
      { name: 'Francisco Gento', country: 'Spain', position: 'Forward', clubs: ['Real Madrid'], birthYear: 1933, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 169, hair: 'dark', beard: false }
    ],
    '1960-1970': [
      { name: 'Ruud Gullit', country: 'Netherlands', position: 'Midfielder', clubs: ['AC Milan', 'Chelsea'], birthYear: 1962, worldCup: false, euro: true, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 191, hair: 'dark', beard: false },
      { name: 'Marco van Basten', country: 'Netherlands', position: 'Forward', clubs: ['AC Milan'], birthYear: 1964, worldCup: false, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 188, hair: 'blonde', beard: false },
      { name: 'Frank Rijkaard', country: 'Netherlands', position: 'Midfielder', clubs: ['AC Milan'], birthYear: 1962, worldCup: false, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 190, hair: 'dark', beard: false },
      { name: 'Roberto Baggio', country: 'Italy', position: 'Forward', clubs: ['Juventus', 'AC Milan'], birthYear: 1967, worldCup: false, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Lothar Matthäus', country: 'Germany', position: 'Midfielder', clubs: ['Bayern Munich', 'Inter Milan'], birthYear: 1961, worldCup: true, euro: true, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: true, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Gary Lineker', country: 'England', position: 'Forward', clubs: ['Barcelona', 'Tottenham'], birthYear: 1960, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Jean-Pierre Papin', country: 'France', position: 'Forward', clubs: ['Marseille', 'AC Milan'], birthYear: 1963, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 173, hair: 'dark', beard: false },
      { name: 'Matthias Sammer', country: 'Germany', position: 'Defender', clubs: ['Borussia Dortmund'], birthYear: 1967, worldCup: false, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 182, hair: 'blonde', beard: false },
      { name: 'Hristo Stoichkov', country: 'Bulgaria', position: 'Forward', clubs: ['Barcelona'], birthYear: 1966, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Paul Gascoigne', country: 'England', position: 'Midfielder', clubs: ['Tottenham', 'Lazio'], birthYear: 1967, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Alan Shearer', country: 'England', position: 'Forward', clubs: ['Blackburn Rovers', 'Newcastle'], birthYear: 1970, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Franco Baresi', country: 'Italy', position: 'Defender', clubs: ['AC Milan'], birthYear: 1960, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 176, hair: 'dark', beard: false },
      { name: 'Peter Schmeichel', country: 'Denmark', position: 'Goalkeeper', clubs: ['Manchester United'], birthYear: 1963, worldCup: false, euro: true, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 193, hair: 'light', beard: false },
      { name: 'Ronald Koeman', country: 'Netherlands', position: 'Defender', clubs: ['Barcelona', 'PSV'], birthYear: 1963, worldCup: false, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 181, hair: 'blonde', beard: false },
      { name: 'Michael Laudrup', country: 'Denmark', position: 'Midfielder', clubs: ['Barcelona', 'Real Madrid'], birthYear: 1964, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Dennis Bergkamp', country: 'Netherlands', position: 'Forward', clubs: ['Ajax', 'Inter Milan', 'Arsenal'], birthYear: 1969, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Roy Keane', country: 'Ireland', position: 'Midfielder', clubs: ['Manchester United'], birthYear: 1971, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'ginger', beard: true },
      { name: 'Didier Deschamps', country: 'France', position: 'Midfielder', clubs: ['Juventus', 'Marseille', 'Chelsea'], birthYear: 1968, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: true, height: 174, hair: 'dark', beard: false },
      { name: 'David Ginola', country: 'France', position: 'Forward', clubs: ['PSG', 'Tottenham'], birthYear: 1967, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 186, hair: 'dark', beard: false },
      { name: 'Bixente Lizarazu', country: 'France', position: 'Defender', clubs: ['Bayern Munich'], birthYear: 1969, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 169, hair: 'dark', beard: false },
      { name: 'Gianfranco Zola', country: 'Italy', position: 'Forward', clubs: ['Napoli', 'Chelsea'], birthYear: 1966, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 168, hair: 'dark', beard: false },
      { name: 'Davor Šuker', country: 'Croatia', position: 'Forward', clubs: ['Real Madrid', 'Arsenal'], birthYear: 1968, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Andreas Köpke', country: 'Germany', position: 'Goalkeeper', clubs: ['Marseille'], birthYear: 1962, worldCup: true, euro: true, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 182, hair: 'light', beard: false },
      { name: 'Dejan Savićević', country: 'Montenegro', position: 'Midfielder', clubs: ['AC Milan'], birthYear: 1966, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 181, hair: 'dark', beard: false }
    ],
    '1970-1980': [
      { name: 'Zinedine Zidane', country: 'France', position: 'Midfielder', clubs: ['Juventus', 'Real Madrid'], birthYear: 1972, worldCup: true, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 185, hair: 'bald', beard: false },
      { name: 'Thierry Henry', country: 'France', position: 'Forward', clubs: ['Arsenal', 'Barcelona'], birthYear: 1977, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 188, hair: 'dark', beard: false },
      { name: 'Pavel Nedvěd', country: 'Czech Republic', position: 'Midfielder', clubs: ['Juventus'], birthYear: 1972, worldCup: false, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 177, hair: 'blonde', beard: false },
      { name: 'Raúl', country: 'Spain', position: 'Forward', clubs: ['Real Madrid'], birthYear: 1977, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Andriy Shevchenko', country: 'Ukraine', position: 'Forward', clubs: ['AC Milan', 'Chelsea'], birthYear: 1976, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Michael Owen', country: 'England', position: 'Forward', clubs: ['Liverpool', 'Real Madrid'], birthYear: 1979, worldCup: false, euro: false, championsLeague: false, ballonDor: true, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Francesco Totti', country: 'Italy', position: 'Forward', clubs: ['Roma'], birthYear: 1976, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Andrea Pirlo', country: 'Italy', position: 'Midfielder', clubs: ['AC Milan', 'Juventus'], birthYear: 1979, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 177, hair: 'dark', beard: true },
      { name: 'Frank Lampard', country: 'England', position: 'Midfielder', clubs: ['Chelsea'], birthYear: 1978, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 184, hair: 'dark', beard: false },
      { name: 'Steven Gerrard', country: 'England', position: 'Midfielder', clubs: ['Liverpool'], birthYear: 1980, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Xavi', country: 'Spain', position: 'Midfielder', clubs: ['Barcelona'], birthYear: 1980, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 170, hair: 'dark', beard: false },
      { name: 'Paolo Maldini', country: 'Italy', position: 'Defender', clubs: ['AC Milan'], birthYear: 1968, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 186, hair: 'dark', beard: false },
      { name: 'Patrick Vieira', country: 'France', position: 'Midfielder', clubs: ['Arsenal', 'Juventus', 'Inter Milan'], birthYear: 1976, worldCup: true, euro: true, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 193, hair: 'dark', beard: false },
      { name: 'Petr Čech', country: 'Czech Republic', position: 'Goalkeeper', clubs: ['Chelsea'], birthYear: 1982, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 196, hair: 'dark', beard: false },
      { name: 'Carles Puyol', country: 'Spain', position: 'Defender', clubs: ['Barcelona'], birthYear: 1978, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: true },
      { name: 'Edwin van der Sar', country: 'Netherlands', position: 'Goalkeeper', clubs: ['Ajax', 'Juventus', 'Manchester United'], birthYear: 1970, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 197, hair: 'dark', beard: false },
      { name: 'Oliver Kahn', country: 'Germany', position: 'Goalkeeper', clubs: ['Bayern Munich'], birthYear: 1969, worldCup: false, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 188, hair: 'light', beard: false },
      { name: 'Rio Ferdinand', country: 'England', position: 'Defender', clubs: ['Manchester United'], birthYear: 1978, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 189, hair: 'dark', beard: false },
      { name: 'Alessandro Nesta', country: 'Italy', position: 'Defender', clubs: ['Lazio', 'AC Milan'], birthYear: 1976, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 187, hair: 'dark', beard: false },
      { name: 'Ryan Giggs', country: 'Wales', position: 'Midfielder', clubs: ['Manchester United'], birthYear: 1973, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 179, hair: 'dark', beard: false },
      { name: 'Claude Makélélé', country: 'France', position: 'Midfielder', clubs: ['Real Madrid', 'Chelsea'], birthYear: 1973, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 174, hair: 'bald', beard: false },
      { name: 'Lilian Thuram', country: 'France', position: 'Defender', clubs: ['Juventus', 'Barcelona'], birthYear: 1972, worldCup: true, euro: true, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Marcel Desailly', country: 'France', position: 'Defender', clubs: ['AC Milan', 'Chelsea'], birthYear: 1968, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Edgar Davids', country: 'Netherlands', position: 'Midfielder', clubs: ['Ajax', 'Juventus', 'Barcelona'], birthYear: 1973, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 169, hair: 'dark', beard: true }
    ],
    '1980-1990': [
      { name: 'Cristiano Ronaldo', country: 'Portugal', position: 'Forward', clubs: ['Manchester United', 'Real Madrid', 'Juventus'], birthYear: 1985, worldCup: false, euro: true, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 187, hair: 'dark', beard: false },
      { name: 'Luka Modrić', country: 'Croatia', position: 'Midfielder', clubs: ['Tottenham', 'Real Madrid'], birthYear: 1985, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 172, hair: 'light', beard: false },
      { name: 'Andrés Iniesta', country: 'Spain', position: 'Midfielder', clubs: ['Barcelona'], birthYear: 1984, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 171, hair: 'dark', beard: false },
      { name: 'Sergio Ramos', country: 'Spain', position: 'Defender', clubs: ['Real Madrid', 'PSG'], birthYear: 1986, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 184, hair: 'dark', beard: true },
      { name: 'Manuel Neuer', country: 'Germany', position: 'Goalkeeper', clubs: ['Bayern Munich'], birthYear: 1986, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 193, hair: 'blonde', beard: false },
      { name: 'Wayne Rooney', country: 'England', position: 'Forward', clubs: ['Manchester United'], birthYear: 1985, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 176, hair: 'dark', beard: false },
      { name: 'Mesut Özil', country: 'Germany', position: 'Midfielder', clubs: ['Real Madrid', 'Arsenal'], birthYear: 1988, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Zlatan Ibrahimović', country: 'Sweden', position: 'Forward', clubs: ['Juventus', 'Barcelona', 'AC Milan', 'PSG', 'Manchester United'], birthYear: 1981, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: true, bundesliga: false, ligue1: true, height: 195, hair: 'dark', beard: false },
      { name: 'Robert Lewandowski', country: 'Poland', position: 'Forward', clubs: ['Borussia Dortmund', 'Bayern Munich', 'Barcelona'], birthYear: 1988, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: true, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Thomas Müller', country: 'Germany', position: 'Forward', clubs: ['Bayern Munich'], birthYear: 1989, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 186, hair: 'dark', beard: false },
      { name: 'Toni Kroos', country: 'Germany', position: 'Midfielder', clubs: ['Bayern Munich', 'Real Madrid'], birthYear: 1990, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: true, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Cesc Fàbregas', country: 'Spain', position: 'Midfielder', clubs: ['Arsenal', 'Barcelona', 'Chelsea'], birthYear: 1987, worldCup: true, euro: true, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: true },
      { name: 'Gerard Piqué', country: 'Spain', position: 'Defender', clubs: ['Barcelona', 'Manchester United'], birthYear: 1987, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 194, hair: 'dark', beard: false },
      { name: 'David Silva', country: 'Spain', position: 'Midfielder', clubs: ['Manchester City'], birthYear: 1986, worldCup: true, euro: true, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 170, hair: 'dark', beard: true },
      { name: 'Philipp Lahm', country: 'Germany', position: 'Defender', clubs: ['Bayern Munich'], birthYear: 1983, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 170, hair: 'dark', beard: false },
      { name: 'Giorgio Chiellini', country: 'Italy', position: 'Defender', clubs: ['Juventus'], birthYear: 1984, worldCup: false, euro: true, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 187, hair: 'dark', beard: true },
      { name: 'Gianluigi Buffon', country: 'Italy', position: 'Goalkeeper', clubs: ['Juventus', 'PSG'], birthYear: 1978, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: true, height: 192, hair: 'dark', beard: false },
      { name: 'Gareth Bale', country: 'Wales', position: 'Forward', clubs: ['Tottenham', 'Real Madrid'], birthYear: 1989, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Arjen Robben', country: 'Netherlands', position: 'Forward', clubs: ['Chelsea', 'Real Madrid', 'Bayern Munich'], birthYear: 1984, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: true, ligue1: false, height: 180, hair: 'bald', beard: false },
      { name: 'Franck Ribéry', country: 'France', position: 'Forward', clubs: ['Bayern Munich'], birthYear: 1983, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 170, hair: 'dark', beard: false },
      { name: 'Pepe', country: 'Portugal', position: 'Defender', clubs: ['Real Madrid'], birthYear: 1983, worldCup: false, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 188, hair: 'dark', beard: false },
      { name: 'Wesley Sneijder', country: 'Netherlands', position: 'Midfielder', clubs: ['Real Madrid', 'Inter Milan'], birthYear: 1984, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 170, hair: 'dark', beard: false },
      { name: 'Samir Handanovič', country: 'Slovenia', position: 'Goalkeeper', clubs: ['Inter Milan'], birthYear: 1984, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 193, hair: 'dark', beard: false },
      { name: 'Victor Valdés', country: 'Spain', position: 'Goalkeeper', clubs: ['Barcelona'], birthYear: 1982, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Xabi Alonso', country: 'Spain', position: 'Midfielder', clubs: ['Liverpool', 'Real Madrid', 'Bayern Munich'], birthYear: 1981, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: true, ligue1: false, height: 183, hair: 'dark', beard: true },
      { name: 'Alvaro Morata', country: 'Spain', position: 'Forward', clubs: ['Real Madrid', 'Chelsea', 'Atletico Madrid'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 189, hair: 'dark', beard: false }
    ],
    '1990-2000': [
      { name: 'Kevin De Bruyne', country: 'Belgium', position: 'Midfielder', clubs: ['Manchester City'], birthYear: 1991, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 181, hair: 'ginger', beard: false },
      { name: 'Harry Kane', country: 'England', position: 'Forward', clubs: ['Tottenham', 'Bayern Munich'], birthYear: 1993, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 188, hair: 'dark', beard: false },
      { name: 'Kylian Mbappé', country: 'France', position: 'Forward', clubs: ['PSG', 'Real Madrid'], birthYear: 1998, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 178, hair: 'dark', beard: false },
      { name: 'Martin Ødegaard', country: 'Norway', position: 'Midfielder', clubs: ['Real Madrid', 'Arsenal'], birthYear: 1998, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'blonde', beard: true },
      { name: 'Thibaut Courtois', country: 'Belgium', position: 'Goalkeeper', clubs: ['Chelsea', 'Real Madrid'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 199, hair: 'dark', beard: false },
      { name: "N'Golo Kanté", country: 'France', position: 'Midfielder', clubs: ['Leicester City', 'Chelsea'], birthYear: 1991, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 168, hair: 'dark', beard: false },
      { name: 'Antoine Griezmann', country: 'France', position: 'Forward', clubs: ['Atletico Madrid', 'Barcelona'], birthYear: 1991, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 176, hair: 'blonde', beard: false },
      { name: 'Eden Hazard', country: 'Belgium', position: 'Forward', clubs: ['Chelsea', 'Real Madrid'], birthYear: 1991, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Jan Oblak', country: 'Slovenia', position: 'Goalkeeper', clubs: ['Atletico Madrid'], birthYear: 1993, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 188, hair: 'dark', beard: false },
      { name: 'Raheem Sterling', country: 'England', position: 'Forward', clubs: ['Liverpool', 'Manchester City', 'Chelsea'], birthYear: 1994, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 170, hair: 'dark', beard: false },
      { name: 'Paul Pogba', country: 'France', position: 'Midfielder', clubs: ['Juventus', 'Manchester United'], birthYear: 1993, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 191, hair: 'dark', beard: false },
      { name: 'Romelu Lukaku', country: 'Belgium', position: 'Forward', clubs: ['Chelsea', 'Inter Milan', 'Manchester United'], birthYear: 1993, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 191, hair: 'dark', beard: false },
      { name: 'Virgil van Dijk', country: 'Netherlands', position: 'Defender', clubs: ['Liverpool'], birthYear: 1991, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 193, hair: 'dark', beard: false },
      { name: 'Raphaël Varane', country: 'France', position: 'Defender', clubs: ['Real Madrid', 'Manchester United'], birthYear: 1993, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 191, hair: 'dark', beard: false },
      { name: 'Joshua Kimmich', country: 'Germany', position: 'Midfielder', clubs: ['Bayern Munich'], birthYear: 1995, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 177, hair: 'blonde', beard: false },
      { name: 'Bernardo Silva', country: 'Portugal', position: 'Midfielder', clubs: ['Manchester City'], birthYear: 1994, worldCup: false, euro: true, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Andrew Robertson', country: 'Scotland', position: 'Defender', clubs: ['Liverpool'], birthYear: 1994, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Leroy Sané', country: 'Germany', position: 'Forward', clubs: ['Manchester City', 'Bayern Munich'], birthYear: 1996, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Marco Verratti', country: 'Italy', position: 'Midfielder', clubs: ['PSG'], birthYear: 1992, worldCup: true, euro: true, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 165, hair: 'dark', beard: false },
      { name: 'Kalidou Koulibaly', country: 'Senegal', position: 'Defender', clubs: ['Napoli', 'Chelsea'], birthYear: 1991, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 187, hair: 'bald', beard: false },
      { name: 'Aymeric Laporte', country: 'Spain', position: 'Defender', clubs: ['Manchester City', 'Athletic Bilbao'], birthYear: 1994, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 191, hair: 'dark', beard: false }
    ],
    '2000-2010': [
      { name: 'Erling Haaland', country: 'Norway', position: 'Forward', clubs: ['Borussia Dortmund', 'Manchester City'], birthYear: 2000, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 194, hair: 'blonde', beard: false },
      { name: 'Jude Bellingham', country: 'England', position: 'Midfielder', clubs: ['Borussia Dortmund', 'Real Madrid'], birthYear: 2003, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: true, ligue1: false, height: 186, hair: 'dark', beard: false },
      { name: 'Phil Foden', country: 'England', position: 'Midfielder', clubs: ['Manchester City'], birthYear: 2000, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 171, hair: 'blonde', beard: false },
      { name: 'Jamal Musiala', country: 'Germany', position: 'Midfielder', clubs: ['Bayern Munich'], birthYear: 2003, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Bukayo Saka', country: 'England', position: 'Forward', clubs: ['Arsenal'], birthYear: 2001, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Florian Wirtz', country: 'Germany', position: 'Midfielder', clubs: ['Bayer Leverkusen'], birthYear: 2003, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 176, hair: 'dark', beard: false },
      { name: 'Pedri', country: 'Spain', position: 'Midfielder', clubs: ['Barcelona'], birthYear: 2002, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Gavi', country: 'Spain', position: 'Midfielder', clubs: ['Barcelona'], birthYear: 2004, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Eduardo Camavinga', country: 'France', position: 'Midfielder', clubs: ['Real Madrid'], birthYear: 2002, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 182, hair: 'dark', beard: false },
      { name: 'Warren Zaïre-Emery', country: 'France', position: 'Midfielder', clubs: ['PSG'], birthYear: 2006, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 175, hair: 'dark', beard: false },
      { name: 'Rodri', country: 'Spain', position: 'Midfielder', clubs: ['Manchester City'], birthYear: 1996, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 191, hair: 'dark', beard: false },
      { name: 'Ruben Dias', country: 'Portugal', position: 'Defender', clubs: ['Manchester City'], birthYear: 1997, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 187, hair: 'dark', beard: false },
      { name: 'Marc-André ter Stegen', country: 'Germany', position: 'Goalkeeper', clubs: ['Barcelona'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 187, hair: 'blonde', beard: false },
      { name: 'Frenkie de Jong', country: 'Netherlands', position: 'Midfielder', clubs: ['Barcelona'], birthYear: 1997, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Kai Havertz', country: 'Germany', position: 'Forward', clubs: ['Bayer Leverkusen', 'Chelsea', 'Arsenal'], birthYear: 1999, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 193, hair: 'dark', beard: false },
      { name: 'Lautaro Martínez', country: 'Argentina', position: 'Forward', clubs: ['Inter Milan'], birthYear: 1997, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false }
    ]
  },
  'south-america': {
    '1940-1950': [
      { name: 'Nílton Santos', country: 'Brazil', position: 'Defender', clubs: ['Botafogo'], birthYear: 1925, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Héctor Rial', country: 'Argentina', position: 'Forward', clubs: ['Real Madrid'], birthYear: 1928, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Obdulio Varela', country: 'Uruguay', position: 'Midfielder', clubs: ['Peñarol'], birthYear: 1917, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'José Manuel Moreno', country: 'Argentina', position: 'Forward', clubs: ['River Plate'], birthYear: 1916, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false }
    ],
    '1950-1960': [
      { name: 'Pelé', country: 'Brazil', position: 'Forward', clubs: ['Santos'], birthYear: 1940, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Garrincha', country: 'Brazil', position: 'Forward', clubs: ['Botafogo'], birthYear: 1933, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 169, hair: 'dark', beard: false },
      { name: 'Rivelino', country: 'Brazil', position: 'Midfielder', clubs: ['Corinthians'], birthYear: 1946, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 171, hair: 'dark', beard: true },
      { name: 'Tostão', country: 'Brazil', position: 'Forward', clubs: ['Cruzeiro'], birthYear: 1947, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 172, hair: 'dark', beard: false },
      { name: 'Elías Figueroa', country: 'Chile', position: 'Defender', clubs: ['Internacional'], birthYear: 1946, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Djalma Santos', country: 'Brazil', position: 'Defender', clubs: ['Palmeiras'], birthYear: 1929, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Daniel Passarella', country: 'Argentina', position: 'Defender', clubs: ['Fiorentina', 'Inter Milan'], birthYear: 1953, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Gérson', country: 'Brazil', position: 'Midfielder', clubs: ['Botafogo'], birthYear: 1941, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Diego Maradona', country: 'Argentina', position: 'Forward', clubs: ['Barcelona', 'Napoli'], birthYear: 1960, worldCup: true, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 165, hair: 'dark', beard: false },
      { name: 'Sócrates', country: 'Brazil', position: 'Midfielder', clubs: ['Corinthians'], birthYear: 1954, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 192, hair: 'dark', beard: true },
      { name: 'Zico', country: 'Brazil', position: 'Midfielder', clubs: ['Flamengo', 'Udinese'], birthYear: 1953, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 172, hair: 'dark', beard: false },
      { name: 'Falcão', country: 'Brazil', position: 'Midfielder', clubs: ['Roma'], birthYear: 1953, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 177, hair: 'dark', beard: false },
      { name: 'Careca', country: 'Brazil', position: 'Forward', clubs: ['Napoli'], birthYear: 1960, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 172, hair: 'bald', beard: false },
      { name: 'Enzo Francescoli', country: 'Uruguay', position: 'Midfielder', clubs: ['River Plate', 'Marseille'], birthYear: 1961, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 179, hair: 'dark', beard: false },
      { name: 'Mario Kempes', country: 'Argentina', position: 'Forward', clubs: ['Valencia'], birthYear: 1954, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 176, hair: 'dark', beard: false },
      { name: 'Jairzinho', country: 'Brazil', position: 'Forward', clubs: ['Botafogo', 'Marseille'], birthYear: 1944, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Teófilo Cubillas', country: 'Peru', position: 'Midfielder', clubs: ['FC Porto'], birthYear: 1949, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Gilmar', country: 'Brazil', position: 'Goalkeeper', clubs: ['Santos'], birthYear: 1930, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 181, hair: 'dark', beard: false },
      { name: 'Ademir de Menezes', country: 'Brazil', position: 'Forward', clubs: ['Vasco da Gama'], birthYear: 1922, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false }
    ],
    '1960-1970': [
      { name: 'Romário', country: 'Brazil', position: 'Forward', clubs: ['PSV', 'Barcelona'], birthYear: 1966, worldCup: true, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 167, hair: 'dark', beard: false },
      { name: 'Gabriel Batistuta', country: 'Argentina', position: 'Forward', clubs: ['Fiorentina', 'Roma'], birthYear: 1969, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Carlos Valderrama', country: 'Colombia', position: 'Midfielder', clubs: ['Montpellier'], birthYear: 1961, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 175, hair: 'blonde', beard: false },
      { name: 'Claudio Caniggia', country: 'Argentina', position: 'Forward', clubs: ['Atalanta', 'Roma'], birthYear: 1967, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 175, hair: 'blonde', beard: false },
      { name: 'Bebeto', country: 'Brazil', position: 'Forward', clubs: ['Deportivo'], birthYear: 1964, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Jorginho', country: 'Brazil', position: 'Midfielder', clubs: ['Bayern Munich'], birthYear: 1964, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Iván Zamorano', country: 'Chile', position: 'Forward', clubs: ['Real Madrid', 'Inter Milan'], birthYear: 1967, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Marcelo Salas', country: 'Chile', position: 'Forward', clubs: ['Lazio', 'Juventus'], birthYear: 1974, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Cláudio Taffarel', country: 'Brazil', position: 'Goalkeeper', clubs: ['Parma', 'Galatasaray'], birthYear: 1966, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Cafú', country: 'Brazil', position: 'Defender', clubs: ['Roma', 'AC Milan'], birthYear: 1970, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 176, hair: 'bald', beard: false },
      { name: 'Roberto Ayala', country: 'Argentina', position: 'Defender', clubs: ['Valencia', 'AC Milan'], birthYear: 1973, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 177, hair: 'dark', beard: false },
      { name: 'José Luis Chilavert', country: 'Paraguay', position: 'Goalkeeper', clubs: ['Vélez Sarsfield', 'Zaragoza'], birthYear: 1965, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 188, hair: 'blonde', beard: true },
      { name: 'Ariel Ortega', country: 'Argentina', position: 'Forward', clubs: ['River Plate', 'Valencia'], birthYear: 1974, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 170, hair: 'dark', beard: false },
      { name: 'Dunga', country: 'Brazil', position: 'Midfielder', clubs: ['Fiorentina'], birthYear: 1963, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 177, hair: 'dark', beard: false }
    ],
    '1970-1980': [
      { name: 'Ronaldo Nazário', country: 'Brazil', position: 'Forward', clubs: ['Barcelona', 'Inter Milan', 'Real Madrid'], birthYear: 1976, worldCup: true, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Rivaldo', country: 'Brazil', position: 'Forward', clubs: ['Barcelona'], birthYear: 1972, worldCup: true, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 186, hair: 'dark', beard: false },
      { name: 'Ronaldinho', country: 'Brazil', position: 'Forward', clubs: ['Barcelona', 'AC Milan'], birthYear: 1980, worldCup: true, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 181, hair: 'dark', beard: false },
      { name: 'Juan Román Riquelme', country: 'Argentina', position: 'Midfielder', clubs: ['Barcelona', 'Villarreal'], birthYear: 1978, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 182, hair: 'dark', beard: false },
      { name: 'Hernán Crespo', country: 'Argentina', position: 'Forward', clubs: ['Parma', 'Inter Milan', 'Chelsea'], birthYear: 1975, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 184, hair: 'dark', beard: false },
      { name: 'Adriano', country: 'Brazil', position: 'Forward', clubs: ['Inter Milan'], birthYear: 1982, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 189, hair: 'dark', beard: false },
      { name: 'Roberto Carlos', country: 'Brazil', position: 'Defender', clubs: ['Real Madrid'], birthYear: 1973, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 168, hair: 'dark', beard: false },
      { name: 'Javier Saviola', country: 'Argentina', position: 'Forward', clubs: ['Barcelona', 'Real Madrid'], birthYear: 1981, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 168, hair: 'dark', beard: false },
      { name: 'Kaká', country: 'Brazil', position: 'Midfielder', clubs: ['AC Milan', 'Real Madrid'], birthYear: 1982, worldCup: true, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 186, hair: 'dark', beard: false },
      { name: 'Robinho', country: 'Brazil', position: 'Forward', clubs: ['Real Madrid', 'Manchester City'], birthYear: 1984, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 172, hair: 'dark', beard: false },
      { name: 'Walter Samuel', country: 'Argentina', position: 'Defender', clubs: ['Real Madrid', 'Inter Milan'], birthYear: 1978, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Gabriel Heinze', country: 'Argentina', position: 'Defender', clubs: ['PSG', 'Manchester United', 'Real Madrid'], birthYear: 1978, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 178, hair: 'dark', beard: false },
      { name: 'Juan Sebastián Verón', country: 'Argentina', position: 'Midfielder', clubs: ['Lazio', 'Manchester United', 'Inter Milan'], birthYear: 1975, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Javier Zanetti', country: 'Argentina', position: 'Defender', clubs: ['Inter Milan'], birthYear: 1973, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Gilberto Silva', country: 'Brazil', position: 'Midfielder', clubs: ['Arsenal'], birthYear: 1976, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false }
    ],
    '1980-1990': [
      { name: 'Lionel Messi', country: 'Argentina', position: 'Forward', clubs: ['Barcelona', 'PSG', 'Inter Miami'], birthYear: 1987, worldCup: true, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 170, hair: 'dark', beard: true },
      { name: 'Luis Suárez', country: 'Uruguay', position: 'Forward', clubs: ['Liverpool', 'Barcelona'], birthYear: 1987, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 182, hair: 'dark', beard: true },
      { name: 'Sergio Agüero', country: 'Argentina', position: 'Forward', clubs: ['Manchester City', 'Barcelona'], birthYear: 1988, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Alexis Sánchez', country: 'Chile', position: 'Forward', clubs: ['Barcelona', 'Arsenal'], birthYear: 1988, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 169, hair: 'dark', beard: false },
      { name: 'James Rodríguez', country: 'Colombia', position: 'Midfielder', clubs: ['Real Madrid', 'Bayern Munich'], birthYear: 1991, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: true, ligue1: false, height: 180, hair: 'dark', beard: true },
      { name: 'Arturo Vidal', country: 'Chile', position: 'Midfielder', clubs: ['Juventus', 'Bayern Munich', 'Barcelona'], birthYear: 1987, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: true, bundesliga: true, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Radamel Falcao', country: 'Colombia', position: 'Forward', clubs: ['Atletico Madrid', 'Monaco'], birthYear: 1986, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 177, hair: 'dark', beard: false },
      { name: 'Ángel Di María', country: 'Argentina', position: 'Midfielder', clubs: ['Real Madrid', 'Manchester United', 'PSG'], birthYear: 1988, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 180, hair: 'dark', beard: false },
      { name: 'Paulo Dybala', country: 'Argentina', position: 'Forward', clubs: ['Juventus', 'Roma'], birthYear: 1993, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 177, hair: 'dark', beard: true },
      { name: 'Edinson Cavani', country: 'Uruguay', position: 'Forward', clubs: ['Napoli', 'PSG', 'Manchester United'], birthYear: 1987, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: true, height: 184, hair: 'dark', beard: false },
      { name: 'Marcelo', country: 'Brazil', position: 'Defender', clubs: ['Real Madrid'], birthYear: 1988, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Diego Godín', country: 'Uruguay', position: 'Defender', clubs: ['Atletico Madrid'], birthYear: 1986, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Neymar', country: 'Brazil', position: 'Forward', clubs: ['Barcelona', 'PSG'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 175, hair: 'dark', beard: false },
      { name: 'Alisson Becker', country: 'Brazil', position: 'Goalkeeper', clubs: ['Roma', 'Liverpool'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 193, hair: 'dark', beard: true },
      { name: 'Casemiro', country: 'Brazil', position: 'Midfielder', clubs: ['Real Madrid', 'Manchester United'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Marquinhos', country: 'Brazil', position: 'Defender', clubs: ['PSG'], birthYear: 1994, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 183, hair: 'dark', beard: false },
      { name: 'Filipe Luís', country: 'Brazil', position: 'Defender', clubs: ['Atletico Madrid', 'Chelsea'], birthYear: 1985, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 186, hair: 'dark', beard: false },
      { name: 'Lucas Moura', country: 'Brazil', position: 'Forward', clubs: ['PSG', 'Tottenham'], birthYear: 1992, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 172, hair: 'dark', beard: false }
    ],
    '1990-2000': [
      { name: 'Vinícius Júnior', country: 'Brazil', position: 'Forward', clubs: ['Real Madrid'], birthYear: 2000, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 176, hair: 'dark', beard: false },
      { name: 'Rodrygo', country: 'Brazil', position: 'Forward', clubs: ['Real Madrid'], birthYear: 2001, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Julián Álvarez', country: 'Argentina', position: 'Forward', clubs: ['Manchester City'], birthYear: 2000, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 170, hair: 'dark', beard: false },
      { name: 'Éder Militão', country: 'Brazil', position: 'Defender', clubs: ['Real Madrid'], birthYear: 1998, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 186, hair: 'dark', beard: false },
      { name: 'Federico Valverde', country: 'Uruguay', position: 'Midfielder', clubs: ['Real Madrid'], birthYear: 1998, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 182, hair: 'dark', beard: false },
      { name: 'Enzo Fernández', country: 'Argentina', position: 'Midfielder', clubs: ['Chelsea'], birthYear: 2001, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false }
    ]
  },
  africa: {
    '1960-1970': [
      { name: 'George Weah', country: 'Liberia', position: 'Forward', clubs: ['AC Milan', 'PSG', 'Chelsea'], birthYear: 1966, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: true, height: 185, hair: 'dark', beard: false },
      { name: 'Abedi Pele', country: 'Ghana', position: 'Forward', clubs: ['Marseille'], birthYear: 1964, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 175, hair: 'dark', beard: false },
      { name: 'Roger Milla', country: 'Cameroon', position: 'Forward', clubs: ['Monaco'], birthYear: 1952, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 176, hair: 'dark', beard: false },
      { name: 'Salif Keïta', country: 'Mali', position: 'Forward', clubs: ['Saint-Étienne'], birthYear: 1946, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 180, hair: 'dark', beard: false }
    ],
    '1970-1980': [
      { name: 'Jay-Jay Okocha', country: 'Nigeria', position: 'Midfielder', clubs: ['PSG', 'Bolton'], birthYear: 1973, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 173, hair: 'dark', beard: false },
      { name: 'Nwankwo Kanu', country: 'Nigeria', position: 'Forward', clubs: ['Ajax', 'Inter Milan', 'Arsenal'], birthYear: 1976, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 197, hair: 'dark', beard: false },
      { name: 'Didier Drogba', country: 'Ivory Coast', position: 'Forward', clubs: ['Chelsea'], birthYear: 1978, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 188, hair: 'bald', beard: false },
      { name: "Samuel Eto'o", country: 'Cameroon', position: 'Forward', clubs: ['Barcelona', 'Inter Milan'], birthYear: 1981, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Michael Essien', country: 'Ghana', position: 'Midfielder', clubs: ['Chelsea', 'Real Madrid'], birthYear: 1982, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Yaya Touré', country: 'Ivory Coast', position: 'Midfielder', clubs: ['Barcelona', 'Manchester City'], birthYear: 1983, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 188, hair: 'bald', beard: false },
      { name: 'Sulley Muntari', country: 'Ghana', position: 'Midfielder', clubs: ['Inter Milan', 'AC Milan'], birthYear: 1984, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'John Obi Mikel', country: 'Nigeria', position: 'Midfielder', clubs: ['Chelsea'], birthYear: 1987, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 188, hair: 'dark', beard: false },
      { name: 'Asamoah Gyan', country: 'Ghana', position: 'Forward', clubs: ['Sunderland', 'Udinese'], birthYear: 1985, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Kolo Touré', country: 'Ivory Coast', position: 'Defender', clubs: ['Arsenal', 'Manchester City', 'Liverpool'], birthYear: 1981, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: false }
    ],
    '1980-1990': [
      { name: 'Mohamed Salah', country: 'Egypt', position: 'Forward', clubs: ['Chelsea', 'Roma', 'Liverpool'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: true },
      { name: 'Riyad Mahrez', country: 'Algeria', position: 'Forward', clubs: ['Leicester City', 'Manchester City'], birthYear: 1991, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 179, hair: 'dark', beard: true },
      { name: 'Sadio Mané', country: 'Senegal', position: 'Forward', clubs: ['Liverpool', 'Bayern Munich'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Pierre-Emerick Aubameyang', country: 'Gabon', position: 'Forward', clubs: ['Borussia Dortmund', 'Arsenal'], birthYear: 1989, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 187, hair: 'dark', beard: false },
      { name: 'Naby Keïta', country: 'Guinea', position: 'Midfielder', clubs: ['RB Leipzig', 'Liverpool'], birthYear: 1995, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 172, hair: 'dark', beard: false },
      { name: 'Wilfried Zaha', country: 'Ivory Coast', position: 'Forward', clubs: ['Manchester United', 'Crystal Palace'], birthYear: 1992, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Thomas Partey', country: 'Ghana', position: 'Midfielder', clubs: ['Atletico Madrid', 'Arsenal'], birthYear: 1993, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Hakim Ziyech', country: 'Morocco', position: 'Midfielder', clubs: ['Ajax', 'Chelsea'], birthYear: 1993, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Édouard Mendy', country: 'Senegal', position: 'Goalkeeper', clubs: ['Chelsea'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 197, hair: 'dark', beard: false },
      { name: 'Victor Wanyama', country: 'Kenya', position: 'Midfielder', clubs: ['Celtic', 'Southampton', 'Tottenham'], birthYear: 1991, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 188, hair: 'dark', beard: false }
    ],
    '1990-2000': [
      { name: 'Victor Osimhen', country: 'Nigeria', position: 'Forward', clubs: ['Napoli'], birthYear: 1998, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Achraf Hakimi', country: 'Morocco', position: 'Defender', clubs: ['Inter Milan', 'PSG'], birthYear: 1998, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: true, height: 181, hair: 'dark', beard: false },
      { name: 'Sofyan Amrabat', country: 'Morocco', position: 'Midfielder', clubs: ['Fiorentina', 'Manchester United'], birthYear: 1996, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: true }
    ]
  },
  asia: {
    '1970-1980': [
      { name: 'Park Ji-sung', country: 'South Korea', position: 'Midfielder', clubs: ['PSV', 'Manchester United'], birthYear: 1981, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Hidetoshi Nakata', country: 'Japan', position: 'Midfielder', clubs: ['Roma', 'Parma'], birthYear: 1977, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Shinji Kagawa', country: 'Japan', position: 'Midfielder', clubs: ['Borussia Dortmund', 'Manchester United'], birthYear: 1989, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Ali Daei', country: 'Iran', position: 'Forward', clubs: ['Bayern Munich', 'Hertha Berlin'], birthYear: 1969, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 192, hair: 'dark', beard: false },
      { name: 'Cha Bum-kun', country: 'South Korea', position: 'Forward', clubs: ['Eintracht Frankfurt', 'Bayer Leverkusen'], birthYear: 1953, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 179, hair: 'dark', beard: false }
    ],
    '1980-1990': [
      { name: 'Son Heung-min', country: 'South Korea', position: 'Forward', clubs: ['Bayer Leverkusen', 'Tottenham'], birthYear: 1992, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Shinji Okazaki', country: 'Japan', position: 'Forward', clubs: ['Leicester City'], birthYear: 1986, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Ki Sung-yueng', country: 'South Korea', position: 'Midfielder', clubs: ['Swansea City', 'Newcastle'], birthYear: 1989, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 186, hair: 'dark', beard: false },
      { name: 'Tim Cahill', country: 'Australia', position: 'Midfielder', clubs: ['Everton'], birthYear: 1979, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false }
    ],
    '1990-2000': [
      { name: 'Takefusa Kubo', country: 'Japan', position: 'Forward', clubs: ['Real Madrid', 'Real Sociedad'], birthYear: 2001, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Lee Kang-in', country: 'South Korea', position: 'Midfielder', clubs: ['Valencia', 'PSG'], birthYear: 2001, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 173, hair: 'dark', beard: false },
      { name: 'Hwang Hee-chan', country: 'South Korea', position: 'Forward', clubs: ['RB Leipzig', 'Wolverhampton'], birthYear: 1996, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 177, hair: 'dark', beard: false }
    ]
  },
  'north-america': {
    '1950-1960': [
      { name: 'Hugo Sánchez', country: 'Mexico', position: 'Forward', clubs: ['Real Madrid', 'Atletico Madrid'], birthYear: 1958, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false }
    ],
    '1970-1980': [
      { name: 'Rafael Márquez', country: 'Mexico', position: 'Defender', clubs: ['Barcelona'], birthYear: 1979, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 182, hair: 'dark', beard: false },
      { name: 'Cuauhtémoc Blanco', country: 'Mexico', position: 'Forward', clubs: ['Valladolid'], birthYear: 1973, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 176, hair: 'dark', beard: false },
      { name: 'Claudio Reyna', country: 'USA', position: 'Midfielder', clubs: ['Rangers', 'Sunderland', 'Man City'], birthYear: 1973, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'light', beard: false },
      { name: 'Kasey Keller', country: 'USA', position: 'Goalkeeper', clubs: ['Leicester City', 'Tottenham'], birthYear: 1969, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 188, hair: 'light', beard: false }
    ],
    '1980-1990': [
      { name: 'Javier Hernández', country: 'Mexico', position: 'Forward', clubs: ['Manchester United', 'Real Madrid'], birthYear: 1988, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Carlos Vela', country: 'Mexico', position: 'Forward', clubs: ['Arsenal', 'Real Sociedad'], birthYear: 1989, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 177, hair: 'dark', beard: true },
      { name: 'Giovani dos Santos', country: 'Mexico', position: 'Forward', clubs: ['Barcelona', 'Tottenham'], birthYear: 1989, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 170, hair: 'dark', beard: false },
      { name: 'Andrés Guardado', country: 'Mexico', position: 'Midfielder', clubs: ['Valencia', 'PSV'], birthYear: 1986, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 169, hair: 'dark', beard: false },
      { name: 'Tim Howard', country: 'USA', position: 'Goalkeeper', clubs: ['Manchester United', 'Everton'], birthYear: 1979, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 191, hair: 'dark', beard: false }
    ],
    '1990-2000': [
      { name: 'Alphonso Davies', country: 'Canada', position: 'Defender', clubs: ['Bayern Munich'], birthYear: 2000, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Hirving Lozano', country: 'Mexico', position: 'Forward', clubs: ['PSV', 'Napoli'], birthYear: 1995, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Christian Pulisic', country: 'USA', position: 'Forward', clubs: ['Borussia Dortmund', 'Chelsea'], birthYear: 1998, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 173, hair: 'dark', beard: false }
    ]
  }
};
