// SPILLERDATABASE - NÅ I EGEN MODUL
export const playerDatabase = {
  europe: {
    '1950-1960': [
      { name: 'Michel Platini', country: 'France', position: 'Midfielder', clubs: ['Juventus'], birthYear: 1955, worldCup: false, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: true, height: 178, hair: 'dark', beard: false },
      { name: 'Karl-Heinz Rummenigge', country: 'Germany', position: 'Forward', clubs: ['Bayern Munich'], birthYear: 1955, worldCup: true, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: true, ligue1: false, height: 182, hair: 'dark', beard: false },
      { name: 'Paolo Rossi', country: 'Italy', position: 'Forward', clubs: ['Juventus'], birthYear: 1956, worldCup: true, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Zbigniew Boniek', country: 'Poland', position: 'Midfielder', clubs: ['Juventus', 'Roma'], birthYear: 1956, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Jean Tigana', country: 'France', position: 'Midfielder', clubs: ['Bordeaux'], birthYear: 1955, worldCup: false, euro: true, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 174, hair: 'dark', beard: false },
      { name: 'Kenny Dalglish', country: 'Scotland', position: 'Forward', clubs: ['Liverpool'], birthYear: 1951, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Kevin Keegan', country: 'England', position: 'Forward', clubs: ['Liverpool', 'Hamburg'], birthYear: 1951, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Bryan Robson', country: 'England', position: 'Midfielder', clubs: ['Manchester United'], birthYear: 1957, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Preben Elkjær', country: 'Denmark', position: 'Forward', clubs: ['Verona'], birthYear: 1957, worldCup: false, euro: true, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Igor Belanov', country: 'Ukraine', position: 'Forward', clubs: ['Dynamo Kyiv'], birthYear: 1960, worldCup: false, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 179, hair: 'dark', beard: false }
    ],
    '1960-1970': [
      { name: 'Ruud Gullit', country: 'Netherlands', position: 'Midfielder', clubs: ['AC Milan', 'Chelsea'], birthYear: 1962, worldCup: false, euro: true, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 191, hair: 'dark', beard: false },
      { name: 'Marco van Basten', country: 'Netherlands', position: 'Forward', clubs: ['AC Milan'], birthYear: 1964, worldCup: false, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 188, hair: 'blonde', beard: false },
      { name: 'Frank Rijkaard', country: 'Netherlands', position: 'Midfielder', clubs: ['AC Milan'], birthYear: 1962, worldCup: false, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 190, hair: 'dark', beard: false },
      { name: 'Roberto Baggio', country: 'Italy', position: 'Forward', clubs: ['Juventus', 'AC Milan'], birthYear: 1967, worldCup: false, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Lothar Matthäus', country: 'Germany', position: 'Midfielder', clubs: ['Bayern Munich', 'Inter Milan'], birthYear: 1961, worldCup: true, euro: true, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: true, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Gary Lineker', country: 'England', position: 'Forward', clubs: ['Barcelona', 'Tottenham'], birthYear: 1960, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Jean-Pierre Papin', country: 'France', position: 'Forward', clubs: ['Marseille', 'AC Milan'], birthYear: 1963, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 173, hair: 'dark', beard: false },
      { name: 'Matthias Sammer', country: 'Germany', position: 'Defender', clubs: ['Borussia Dortmund'], birthYear: 1967, worldCup: false, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 182, hair: 'blonde', beard: false },
      { name: 'Hristo Stoichkov', country: 'Bulgaria', position: 'Forward', clubs: ['Barcelona'], birthYear: 1966, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Paul Gascoigne', country: 'England', position: 'Midfielder', clubs: ['Tottenham', 'Lazio'], birthYear: 1967, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Alan Shearer', country: 'England', position: 'Forward', clubs: ['Blackburn Rovers', 'Newcastle'], birthYear: 1970, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false }
    ],
    '1970-1980': [
      { name: 'Zinedine Zidane', country: 'France', position: 'Midfielder', clubs: ['Juventus', 'Real Madrid'], birthYear: 1972, worldCup: true, euro: true, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 185, hair: 'bald', beard: false },
      { name: 'Thierry Henry', country: 'France', position: 'Forward', clubs: ['Arsenal', 'Barcelona'], birthYear: 1977, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 188, hair: 'dark', beard: false },
      { name: 'Pavel Nedvěd', country: 'Czech Republic', position: 'Midfielder', clubs: ['Juventus'], birthYear: 1972, worldCup: false, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 177, hair: 'blonde', beard: false },
      { name: 'Raúl', country: 'Spain', position: 'Forward', clubs: ['Real Madrid'], birthYear: 1977, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Andriy Shevchenko', country: 'Ukraine', position: 'Forward', clubs: ['AC Milan', 'Chelsea'], birthYear: 1976, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Michael Owen', country: 'England', position: 'Forward', clubs: ['Liverpool', 'Real Madrid'], birthYear: 1979, worldCup: false, euro: false, championsLeague: false, ballonDor: true, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Francesco Totti', country: 'Italy', position: 'Forward', clubs: ['Roma'], birthYear: 1976, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Andrea Pirlo', country: 'Italy', position: 'Midfielder', clubs: ['AC Milan', 'Juventus'], birthYear: 1979, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 177, hair: 'dark', beard: true },
      { name: 'Frank Lampard', country: 'England', position: 'Midfielder', clubs: ['Chelsea'], birthYear: 1978, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 184, hair: 'dark', beard: false },
      { name: 'Steven Gerrard', country: 'England', position: 'Midfielder', clubs: ['Liverpool'], birthYear: 1980, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Xavi', country: 'Spain', position: 'Midfielder', clubs: ['Barcelona'], birthYear: 1980, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 170, hair: 'dark', beard: false }
    ],
    '1980-1990': [
      { name: 'Cristiano Ronaldo', country: 'Portugal', position: 'Forward', clubs: ['Manchester United', 'Real Madrid'], birthYear: 1985, worldCup: false, euro: true, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 187, hair: 'dark', beard: false },
      { name: 'Luka Modrić', country: 'Croatia', position: 'Midfielder', clubs: ['Tottenham', 'Real Madrid'], birthYear: 1985, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 172, hair: 'light', beard: false },
      { name: 'Andrés Iniesta', country: 'Spain', position: 'Midfielder', clubs: ['Barcelona'], birthYear: 1984, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 171, hair: 'dark', beard: false },
      { name: 'Sergio Ramos', country: 'Spain', position: 'Defender', clubs: ['Real Madrid', 'PSG'], birthYear: 1986, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 184, hair: 'dark', beard: true },
      { name: 'Manuel Neuer', country: 'Germany', position: 'Goalkeeper', clubs: ['Bayern Munich'], birthYear: 1986, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 193, hair: 'blonde', beard: false },
      { name: 'Wayne Rooney', country: 'England', position: 'Forward', clubs: ['Manchester United'], birthYear: 1985, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 176, hair: 'dark', beard: false },
      { name: 'Mesut Özil', country: 'Germany', position: 'Midfielder', clubs: ['Real Madrid', 'Arsenal'], birthYear: 1988, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Zlatan Ibrahimović', country: 'Sweden', position: 'Forward', clubs: ['Juventus', 'Barcelona', 'AC Milan', 'PSG', 'Manchester United'], birthYear: 1981, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: true, bundesliga: false, ligue1: true, height: 195, hair: 'dark', beard: false },
      { name: 'Robert Lewandowski', country: 'Poland', position: 'Forward', clubs: ['Borussia Dortmund', 'Bayern Munich'], birthYear: 1988, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Thomas Müller', country: 'Germany', position: 'Forward', clubs: ['Bayern Munich'], birthYear: 1989, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 186, hair: 'dark', beard: false },
      { name: 'Toni Kroos', country: 'Germany', position: 'Midfielder', clubs: ['Bayern Munich', 'Real Madrid'], birthYear: 1990, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: true, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Cesc Fàbregas', country: 'Spain', position: 'Midfielder', clubs: ['Arsenal', 'Barcelona', 'Chelsea'], birthYear: 1987, worldCup: true, euro: true, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: true },
      { name: 'Gerard Piqué', country: 'Spain', position: 'Defender', clubs: ['Barcelona', 'Manchester United'], birthYear: 1987, worldCup: true, euro: true, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 194, hair: 'dark', beard: false },
      { name: 'David Silva', country: 'Spain', position: 'Midfielder', clubs: ['Manchester City'], birthYear: 1986, worldCup: true, euro: true, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 170, hair: 'dark', beard: true }
    ],
    '1990-2000': [
      { name: 'Kevin De Bruyne', country: 'Belgium', position: 'Midfielder', clubs: ['Manchester City'], birthYear: 1991, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 181, hair: 'ginger', beard: false },
      { name: 'Harry Kane', country: 'England', position: 'Forward', clubs: ['Tottenham', 'Bayern Munich'], birthYear: 1993, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 188, hair: 'dark', beard: false },
      { name: 'Kylian Mbappé', country: 'France', position: 'Forward', clubs: ['PSG', 'Real Madrid'], birthYear: 1998, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 178, hair: 'dark', beard: false },
      { name: 'Martin Ødegaard', country: 'Norway', position: 'Midfielder', clubs: ['Real Madrid', 'Arsenal'], birthYear: 1998, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'blonde', beard: true },
      { name: 'Thibaut Courtois', country: 'Belgium', position: 'Goalkeeper', clubs: ['Chelsea', 'Real Madrid'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 199, hair: 'dark', beard: false },
      { name: "N'Golo Kanté", country: 'France', position: 'Midfielder', clubs: ['Leicester City', 'Chelsea'], birthYear: 1991, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 168, hair: 'dark', beard: false },
      { name: 'Antoine Griezmann', country: 'France', position: 'Forward', clubs: ['Atletico Madrid', 'Barcelona'], birthYear: 1991, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 176, hair: 'blonde', beard: false },
      { name: 'Eden Hazard', country: 'Belgium', position: 'Forward', clubs: ['Chelsea', 'Real Madrid'], birthYear: 1991, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Jan Oblak', country: 'Slovenia', position: 'Goalkeeper', clubs: ['Atletico Madrid'], birthYear: 1993, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 188, hair: 'dark', beard: false },
      { name: 'Raheem Sterling', country: 'England', position: 'Forward', clubs: ['Liverpool', 'Manchester City', 'Chelsea'], birthYear: 1994, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 170, hair: 'dark', beard: false },
      { name: 'Paul Pogba', country: 'France', position: 'Midfielder', clubs: ['Juventus', 'Manchester United'], birthYear: 1993, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 191, hair: 'dark', beard: false },
      { name: 'Romelu Lukaku', country: 'Belgium', position: 'Forward', clubs: ['Chelsea', 'Inter Milan', 'Manchester United'], birthYear: 1993, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 191, hair: 'dark', beard: false }
    ],
    '2000-2010': [
      { name: 'Erling Haaland', country: 'Norway', position: 'Forward', clubs: ['Borussia Dortmund', 'Manchester City'], birthYear: 2000, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 194, hair: 'blonde', beard: false },
      { name: 'Jude Bellingham', country: 'England', position: 'Midfielder', clubs: ['Borussia Dortmund', 'Real Madrid'], birthYear: 2003, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: true, ligue1: false, height: 186, hair: 'dark', beard: false },
      { name: 'Phil Foden', country: 'England', position: 'Midfielder', clubs: ['Manchester City'], birthYear: 2000, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 171, hair: 'blonde', beard: false },
      { name: 'Jamal Musiala', country: 'Germany', position: 'Midfielder', clubs: ['Bayern Munich'], birthYear: 2003, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Bukayo Saka', country: 'England', position: 'Forward', clubs: ['Arsenal'], birthYear: 2001, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Florian Wirtz', country: 'Germany', position: 'Midfielder', clubs: ['Bayer Leverkusen'], birthYear: 2003, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 176, hair: 'dark', beard: false },
      { name: 'Pedri', country: 'Spain', position: 'Midfielder', clubs: ['Barcelona'], birthYear: 2002, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Gavi', country: 'Spain', position: 'Midfielder', clubs: ['Barcelona'], birthYear: 2004, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Eduardo Camavinga', country: 'France', position: 'Midfielder', clubs: ['Real Madrid'], birthYear: 2002, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 182, hair: 'dark', beard: false },
      { name: 'Warren Zaïre-Emery', country: 'France', position: 'Midfielder', clubs: ['PSG'], birthYear: 2006, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 175, hair: 'dark', beard: false }
    ]
  },
  'south-america': {
    '1950-1960': [
      { name: 'Diego Maradona', country: 'Argentina', position: 'Forward', clubs: ['Barcelona', 'Napoli'], birthYear: 1960, worldCup: true, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 165, hair: 'dark', beard: false },
      { name: 'Sócrates', country: 'Brazil', position: 'Midfielder', clubs: ['Corinthians'], birthYear: 1954, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 192, hair: 'dark', beard: true },
      { name: 'Zico', country: 'Brazil', position: 'Midfielder', clubs: ['Flamengo', 'Udinese'], birthYear: 1953, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 172, hair: 'dark', beard: false },
      { name: 'Falcão', country: 'Brazil', position: 'Midfielder', clubs: ['Roma'], birthYear: 1953, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 177, hair: 'dark', beard: false },
      { name: 'Careca', country: 'Brazil', position: 'Forward', clubs: ['Napoli'], birthYear: 1960, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 172, hair: 'bald', beard: false },
      { name: 'Enzo Francescoli', country: 'Uruguay', position: 'Midfielder', clubs: ['River Plate', 'Marseille'], birthYear: 1961, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 179, hair: 'dark', beard: false },
      { name: 'Mario Kempes', country: 'Argentina', position: 'Forward', clubs: ['Valencia'], birthYear: 1954, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 176, hair: 'dark', beard: false },
      { name: 'Jairzinho', country: 'Brazil', position: 'Forward', clubs: ['Botafogo', 'Marseille'], birthYear: 1944, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Teófilo Cubillas', country: 'Peru', position: 'Midfielder', clubs: ['FC Porto'], birthYear: 1949, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false }
    ],
    '1960-1970': [
      { name: 'Romário', country: 'Brazil', position: 'Forward', clubs: ['PSV', 'Barcelona'], birthYear: 1966, worldCup: true, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 167, hair: 'dark', beard: false },
      { name: 'Gabriel Batistuta', country: 'Argentina', position: 'Forward', clubs: ['Fiorentina', 'Roma'], birthYear: 1969, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Carlos Valderrama', country: 'Colombia', position: 'Midfielder', clubs: ['Montpellier'], birthYear: 1961, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 175, hair: 'blonde', beard: false },
      { name: 'Claudio Caniggia', country: 'Argentina', position: 'Forward', clubs: ['Atalanta', 'Roma'], birthYear: 1967, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 175, hair: 'blonde', beard: false },
      { name: 'Bebeto', country: 'Brazil', position: 'Forward', clubs: ['Deportivo'], birthYear: 1964, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Jorginho', country: 'Brazil', position: 'Midfielder', clubs: ['Bayern Munich'], birthYear: 1964, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Iván Zamorano', country: 'Chile', position: 'Forward', clubs: ['Real Madrid', 'Inter Milan'], birthYear: 1967, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Marcelo Salas', country: 'Chile', position: 'Forward', clubs: ['Lazio', 'Juventus'], birthYear: 1974, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Claudio Taffarel', country: 'Brazil', position: 'Goalkeeper', clubs: ['Parma'], birthYear: 1966, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Cafú', country: 'Brazil', position: 'Defender', clubs: ['Roma', 'AC Milan'], birthYear: 1970, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 176, hair: 'bald', beard: false }
    ],
    '1970-1980': [
      { name: 'Ronaldo Nazário', country: 'Brazil', position: 'Forward', clubs: ['Barcelona', 'Inter Milan', 'Real Madrid'], birthYear: 1976, worldCup: true, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Rivaldo', country: 'Brazil', position: 'Forward', clubs: ['Barcelona'], birthYear: 1972, worldCup: true, euro: false, championsLeague: false, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 186, hair: 'dark', beard: false },
      { name: 'Ronaldinho', country: 'Brazil', position: 'Forward', clubs: ['Barcelona', 'AC Milan'], birthYear: 1980, worldCup: true, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 181, hair: 'dark', beard: false },
      { name: 'Juan Román Riquelme', country: 'Argentina', position: 'Midfielder', clubs: ['Barcelona', 'Villarreal'], birthYear: 1978, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 182, hair: 'dark', beard: false },
      { name: 'Hernán Crespo', country: 'Argentina', position: 'Forward', clubs: ['Parma', 'Inter Milan', 'Chelsea'], birthYear: 1975, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 184, hair: 'dark', beard: false },
      { name: 'Adriano', country: 'Brazil', position: 'Forward', clubs: ['Inter Milan'], birthYear: 1982, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 189, hair: 'dark', beard: false },
      { name: 'Roberto Carlos', country: 'Brazil', position: 'Defender', clubs: ['Real Madrid'], birthYear: 1973, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 168, hair: 'dark', beard: false },
      { name: 'Javier Saviola', country: 'Argentina', position: 'Forward', clubs: ['Barcelona', 'Real Madrid'], birthYear: 1981, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 168, hair: 'dark', beard: false },
      { name: 'Kaká', country: 'Brazil', position: 'Midfielder', clubs: ['AC Milan', 'Real Madrid'], birthYear: 1982, worldCup: true, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 186, hair: 'dark', beard: false },
      { name: 'Robinho', country: 'Brazil', position: 'Forward', clubs: ['Real Madrid', 'Manchester City'], birthYear: 1984, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 172, hair: 'dark', beard: false }
    ],
    '1980-1990': [
      { name: 'Lionel Messi', country: 'Argentina', position: 'Forward', clubs: ['Barcelona', 'PSG', 'Inter Miami'], birthYear: 1987, worldCup: true, euro: false, championsLeague: true, ballonDor: true, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 170, hair: 'dark', beard: true },
      { name: 'Luis Suárez', country: 'Uruguay', position: 'Forward', clubs: ['Liverpool', 'Barcelona'], birthYear: 1987, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 182, hair: 'dark', beard: true },
      { name: 'Sergio Agüero', country: 'Argentina', position: 'Forward', clubs: ['Manchester City', 'Barcelona'], birthYear: 1988, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Alexis Sánchez', country: 'Chile', position: 'Forward', clubs: ['Barcelona', 'Arsenal'], birthYear: 1988, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 169, hair: 'dark', beard: false },
      { name: 'James Rodríguez', country: 'Colombia', position: 'Midfielder', clubs: ['Real Madrid', 'Bayern Munich'], birthYear: 1991, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: true, ligue1: false, height: 180, hair: 'dark', beard: true },
      { name: 'Arturo Vidal', country: 'Chile', position: 'Midfielder', clubs: ['Juventus', 'Bayern Munich', 'Barcelona'], birthYear: 1987, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: true, bundesliga: true, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Radamel Falcao', country: 'Colombia', position: 'Forward', clubs: ['Atletico Madrid', 'Monaco'], birthYear: 1986, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 177, hair: 'dark', beard: false },
      { name: 'Ángel Di María', country: 'Argentina', position: 'Midfielder', clubs: ['Real Madrid', 'Manchester United', 'PSG'], birthYear: 1988, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 180, hair: 'dark', beard: false },
      { name: 'Paulo Dybala', country: 'Argentina', position: 'Forward', clubs: ['Juventus', 'Roma'], birthYear: 1993, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 177, hair: 'dark', beard: true },
      { name: 'Edinson Cavani', country: 'Uruguay', position: 'Forward', clubs: ['Napoli', 'PSG', 'Manchester United'], birthYear: 1987, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: true, height: 184, hair: 'dark', beard: false }
    ],
    '1990-2000': [
      { name: 'Neymar', country: 'Brazil', position: 'Forward', clubs: ['Barcelona', 'PSG'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 175, hair: 'dark', beard: false },
      { name: 'Vinícius Júnior', country: 'Brazil', position: 'Forward', clubs: ['Real Madrid'], birthYear: 2000, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 176, hair: 'dark', beard: false },
      { name: 'Rodrygo', country: 'Brazil', position: 'Forward', clubs: ['Real Madrid'], birthYear: 2001, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Lautaro Martínez', country: 'Argentina', position: 'Forward', clubs: ['Inter Milan'], birthYear: 1997, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Julián Álvarez', country: 'Argentina', position: 'Forward', clubs: ['Manchester City'], birthYear: 2000, worldCup: true, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 170, hair: 'dark', beard: false },
      { name: 'Éder Militão', country: 'Brazil', position: 'Defender', clubs: ['Real Madrid'], birthYear: 1998, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 186, hair: 'dark', beard: false },
      { name: 'Alisson Becker', country: 'Brazil', position: 'Goalkeeper', clubs: ['Roma', 'Liverpool'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 193, hair: 'dark', beard: true },
      { name: 'Casemiro', country: 'Brazil', position: 'Midfielder', clubs: ['Real Madrid', 'Manchester United'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Marquinhos', country: 'Brazil', position: 'Defender', clubs: ['PSG'], birthYear: 1994, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 183, hair: 'dark', beard: false },
      { name: 'Federico Valverde', country: 'Uruguay', position: 'Midfielder', clubs: ['Real Madrid'], birthYear: 1998, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 182, hair: 'dark', beard: false }
    ],
    '2000-2010': [
      { name: 'Endrick', country: 'Brazil', position: 'Forward', clubs: ['Real Madrid'], birthYear: 2006, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Enzo Fernández', country: 'Argentina', position: 'Midfielder', clubs: ['Chelsea'], birthYear: 2001, worldCup: true, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Alejandro Garnacho', country: 'Argentina', position: 'Forward', clubs: ['Manchester United'], birthYear: 2004, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false }
    ]
  },
  africa: {
    '1960-1970': [
      { name: 'George Weah', country: 'Liberia', position: 'Forward', clubs: ['AC Milan', 'PSG', 'Chelsea'], birthYear: 1966, worldCup: false, euro: false, championsLeague: true, ballonDor: true, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: true, height: 185, hair: 'dark', beard: false },
      { name: 'Abedi Pele', country: 'Ghana', position: 'Forward', clubs: ['Marseille'], birthYear: 1964, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 175, hair: 'dark', beard: false },
      { name: 'Roger Milla', country: 'Cameroon', position: 'Forward', clubs: ['Monaco'], birthYear: 1952, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 176, hair: 'dark', beard: false }
    ],
    '1970-1980': [
      { name: 'Jay-Jay Okocha', country: 'Nigeria', position: 'Midfielder', clubs: ['PSG', 'Bolton'], birthYear: 1973, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 173, hair: 'dark', beard: false },
      { name: 'Nwankwo Kanu', country: 'Nigeria', position: 'Forward', clubs: ['Ajax', 'Inter Milan', 'Arsenal'], birthYear: 1976, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 197, hair: 'dark', beard: false },
      { name: 'Didier Drogba', country: 'Ivory Coast', position: 'Forward', clubs: ['Chelsea'], birthYear: 1978, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 188, hair: 'bald', beard: false },
      { name: "Samuel Eto'o", country: 'Cameroon', position: 'Forward', clubs: ['Barcelona', 'Inter Milan'], birthYear: 1981, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: true, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Michael Essien', country: 'Ghana', position: 'Midfielder', clubs: ['Chelsea', 'Real Madrid'], birthYear: 1982, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'Emmanuel Adebayor', country: 'Togo', position: 'Forward', clubs: ['Arsenal', 'Manchester City'], birthYear: 1984, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 191, hair: 'dark', beard: false },
      { name: 'Yaya Touré', country: 'Ivory Coast', position: 'Midfielder', clubs: ['Barcelona', 'Manchester City'], birthYear: 1983, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 188, hair: 'bald', beard: false },
      { name: 'Sulley Muntari', country: 'Ghana', position: 'Midfielder', clubs: ['Inter Milan', 'AC Milan'], birthYear: 1984, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 178, hair: 'dark', beard: false },
      { name: 'John Obi Mikel', country: 'Nigeria', position: 'Midfielder', clubs: ['Chelsea'], birthYear: 1987, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 188, hair: 'dark', beard: false },
      { name: 'Asamoah Gyan', country: 'Ghana', position: 'Forward', clubs: ['Sunderland', 'Udinese'], birthYear: 1985, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false }
    ],
    '1980-1990': [
      { name: 'Mohamed Salah', country: 'Egypt', position: 'Forward', clubs: ['Chelsea', 'Roma', 'Liverpool'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: true },
      { name: 'Riyad Mahrez', country: 'Algeria', position: 'Forward', clubs: ['Leicester City', 'Manchester City'], birthYear: 1991, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 179, hair: 'dark', beard: true },
      { name: 'Sadio Mané', country: 'Senegal', position: 'Forward', clubs: ['Liverpool', 'Bayern Munich'], birthYear: 1992, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Pierre-Emerick Aubameyang', country: 'Gabon', position: 'Forward', clubs: ['Borussia Dortmund', 'Arsenal'], birthYear: 1989, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 187, hair: 'dark', beard: false },
      { name: 'Naby Keïta', country: 'Guinea', position: 'Midfielder', clubs: ['RB Leipzig', 'Liverpool'], birthYear: 1995, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 172, hair: 'dark', beard: false },
      { name: 'Wilfried Zaha', country: 'Ivory Coast', position: 'Forward', clubs: ['Manchester United', 'Crystal Palace'], birthYear: 1992, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Thomas Partey', country: 'Ghana', position: 'Midfielder', clubs: ['Atletico Madrid', 'Arsenal'], birthYear: 1993, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Kalidou Koulibaly', country: 'Senegal', position: 'Defender', clubs: ['Napoli', 'Chelsea'], birthYear: 1991, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 187, hair: 'bald', beard: false },
      { name: 'Hakim Ziyech', country: 'Morocco', position: 'Midfielder', clubs: ['Ajax', 'Chelsea'], birthYear: 1993, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 180, hair: 'dark', beard: false },
      { name: 'Nicolas Pépé', country: 'Ivory Coast', position: 'Forward', clubs: ['Lille', 'Arsenal'], birthYear: 1995, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: true, height: 183, hair: 'dark', beard: false }
    ],
    '1990-2000': [
      { name: 'Victor Osimhen', country: 'Nigeria', position: 'Forward', clubs: ['Napoli'], birthYear: 1998, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 185, hair: 'dark', beard: false },
      { name: 'Achraf Hakimi', country: 'Morocco', position: 'Defender', clubs: ['Inter Milan', 'PSG'], birthYear: 1998, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: true, height: 181, hair: 'dark', beard: false },
      { name: 'Sofyan Amrabat', country: 'Morocco', position: 'Midfielder', clubs: ['Fiorentina', 'Manchester United'], birthYear: 1996, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 183, hair: 'dark', beard: true }
    ]
  },
  asia: {
    '1970-1980': [
      { name: 'Park Ji-sung', country: 'South Korea', position: 'Midfielder', clubs: ['PSV', 'Manchester United'], birthYear: 1981, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Hidetoshi Nakata', country: 'Japan', position: 'Midfielder', clubs: ['Roma', 'Parma'], birthYear: 1977, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Shinji Kagawa', country: 'Japan', position: 'Midfielder', clubs: ['Borussia Dortmund', 'Manchester United'], birthYear: 1989, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 175, hair: 'dark', beard: false }
    ],
    '1980-1990': [
      { name: 'Son Heung-min', country: 'South Korea', position: 'Forward', clubs: ['Bayer Leverkusen', 'Tottenham'], birthYear: 1992, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Shinji Okazaki', country: 'Japan', position: 'Forward', clubs: ['Leicester City'], birthYear: 1986, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 174, hair: 'dark', beard: false },
      { name: 'Ki Sung-yueng', country: 'South Korea', position: 'Midfielder', clubs: ['Swansea City', 'Newcastle'], birthYear: 1989, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: false, ligue1: false, height: 186, hair: 'dark', beard: false }
    ],
    '1990-2000': [
      { name: 'Takefusa Kubo', country: 'Japan', position: 'Forward', clubs: ['Real Madrid', 'Real Sociedad'], birthYear: 2001, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 173, hair: 'dark', beard: false },
      { name: 'Lee Kang-in', country: 'South Korea', position: 'Midfielder', clubs: ['Valencia', 'PSG'], birthYear: 2001, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: true, height: 173, hair: 'dark', beard: false },
      { name: 'Hwang Hee-chan', country: 'South Korea', position: 'Forward', clubs: ['RB Leipzig', 'Wolverhampton'], birthYear: 1996, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 177, hair: 'dark', beard: false }
    ]
  },
  'north-america': {
    '1950-1960': [
      { name: 'Hugo Sánchez', country: 'Mexico', position: 'Forward', clubs: ['Real Madrid', 'Atletico Madrid'], birthYear: 1958, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false }
    ],
    '1970-1980': [
      { name: 'Rafael Márquez', country: 'Mexico', position: 'Defender', clubs: ['Barcelona'], birthYear: 1979, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 182, hair: 'dark', beard: false },
      { name: 'Cuauhtémoc Blanco', country: 'Mexico', position: 'Forward', clubs: ['Valladolid'], birthYear: 1973, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 176, hair: 'dark', beard: false }
    ],
    '1980-1990': [
      { name: 'Javier Hernández', country: 'Mexico', position: 'Forward', clubs: ['Manchester United', 'Real Madrid'], birthYear: 1988, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Carlos Vela', country: 'Mexico', position: 'Forward', clubs: ['Arsenal', 'Real Sociedad'], birthYear: 1989, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 177, hair: 'dark', beard: true },
      { name: 'Giovani dos Santos', country: 'Mexico', position: 'Forward', clubs: ['Barcelona', 'Tottenham'], birthYear: 1989, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: true, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 170, hair: 'dark', beard: false },
      { name: 'Andrés Guardado', country: 'Mexico', position: 'Midfielder', clubs: ['Valencia', 'PSV'], birthYear: 1986, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: true, serieA: false, bundesliga: false, ligue1: false, height: 169, hair: 'dark', beard: false }
    ],
    '1990-2000': [
      { name: 'Alphonso Davies', country: 'Canada', position: 'Defender', clubs: ['Bayern Munich'], birthYear: 2000, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: false, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 183, hair: 'dark', beard: false },
      { name: 'Hirving Lozano', country: 'Mexico', position: 'Forward', clubs: ['PSV', 'Napoli'], birthYear: 1995, worldCup: false, euro: false, championsLeague: false, ballonDor: false, premierLeague: false, laLiga: false, serieA: true, bundesliga: false, ligue1: false, height: 175, hair: 'dark', beard: false },
      { name: 'Christian Pulisic', country: 'USA', position: 'Forward', clubs: ['Borussia Dortmund', 'Chelsea'], birthYear: 1998, worldCup: false, euro: false, championsLeague: true, ballonDor: false, premierLeague: true, laLiga: false, serieA: false, bundesliga: true, ligue1: false, height: 173, hair: 'dark', beard: false }
    ]
  }
};
